/*
 TweenJS
 Visit http://createjs.com/ for documentation, updates and examples.

 Copyright (c) 2010 gskinner.com, inc.

 Permission is hereby granted, free of charge, to any person
 obtaining a copy of this software and associated documentation
 files (the "Software"), to deal in the Software without
 restriction, including without limitation the rights to use,
 copy, modify, merge, publish, distribute, sublicense, and/or sell
 copies of the Software, and to permit persons to whom the
 Software is furnished to do so, subject to the following
 conditions:

 The above copyright notice and this permission notice shall be
 included in all copies or substantial portions of the Software.

 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
 OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
 HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
 WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
 OTHER DEALINGS IN THE SOFTWARE.
 Platform.js <https://mths.be/platform>
 Copyright 2014-2018 Benjamin Tan <https://bnjmnt4n.now.sh/>
 Copyright 2011-2013 John-David Dalton
 Available under MIT license <https://mths.be/mit>
*/
this.createjs=this.createjs||{};createjs.extend=function(a,c){function b(){this.constructor=a}b.prototype=c.prototype;return a.prototype=new b};this.createjs=this.createjs||{};createjs.promote=function(a,c){var b=a.prototype,e=Object.getPrototypeOf&&Object.getPrototypeOf(b)||b.__proto__;if(e){b[(c+="_")+"constructor"]=e.constructor;for(var d in e)b.hasOwnProperty(d)&&"function"==typeof e[d]&&(b[c+d]=e[d])}return a};this.createjs=this.createjs||{};
createjs.deprecate=function(a,c){return function(){var b="Deprecated property or method '"+c+"'. See docs for info.";console&&(console.warn?console.warn(b):console.log(b));return a&&a.apply(this,arguments)}};this.createjs=this.createjs||{};
(function(){function a(a,c,d){this.type=a;this.currentTarget=this.target=null;this.eventPhase=0;this.bubbles=!!c;this.cancelable=!!d;this.timeStamp=(new Date).getTime();this.removed=this.immediatePropagationStopped=this.propagationStopped=this.defaultPrevented=!1}var c=a.prototype;c.preventDefault=function(){this.defaultPrevented=this.cancelable&&!0};c.stopPropagation=function(){this.propagationStopped=!0};c.stopImmediatePropagation=function(){this.immediatePropagationStopped=this.propagationStopped=
!0};c.remove=function(){this.removed=!0};c.clone=function(){return new a(this.type,this.bubbles,this.cancelable)};c.set=function(a){for(var b in a)this[b]=a[b];return this};c.toString=function(){return"[Event (type="+this.type+")]"};createjs.Event=a})();this.createjs=this.createjs||{};
(function(){function a(){this._captureListeners=this._listeners=null}var c=a.prototype;a.initialize=function(a){a.addEventListener=c.addEventListener;a.on=c.on;a.removeEventListener=a.off=c.removeEventListener;a.removeAllEventListeners=c.removeAllEventListeners;a.hasEventListener=c.hasEventListener;a.dispatchEvent=c.dispatchEvent;a._dispatchEvent=c._dispatchEvent;a.willTrigger=c.willTrigger};c.addEventListener=function(a,c,d){var b=d?this._captureListeners=this._captureListeners||{}:this._listeners=
this._listeners||{};var e=b[a];e&&this.removeEventListener(a,c,d);(e=b[a])?e.push(c):b[a]=[c];return c};c.on=function(a,c,d,f,g,h){c.handleEvent&&(d=d||c,c=c.handleEvent);d=d||this;return this.addEventListener(a,function(a){c.call(d,a,g);f&&a.remove()},h)};c.removeEventListener=function(a,c,d){if(d=d?this._captureListeners:this._listeners){var b=d[a];if(b)for(var e=0,h=b.length;e<h;e++)if(b[e]==c){1==h?delete d[a]:b.splice(e,1);break}}};c.off=c.removeEventListener;c.removeAllEventListeners=function(a){a?
(this._listeners&&delete this._listeners[a],this._captureListeners&&delete this._captureListeners[a]):this._listeners=this._captureListeners=null};c.dispatchEvent=function(a,c,d){if("string"==typeof a){var b=this._listeners;if(!(c||b&&b[a]))return!0;a=new createjs.Event(a,c,d)}else a.target&&a.clone&&(a=a.clone());try{a.target=this}catch(g){}if(a.bubbles&&this.parent){d=this;for(c=[d];d.parent;)c.push(d=d.parent);b=c.length;for(d=b-1;0<=d&&!a.propagationStopped;d--)c[d]._dispatchEvent(a,1+(0==d));
for(d=1;d<b&&!a.propagationStopped;d++)c[d]._dispatchEvent(a,3)}else this._dispatchEvent(a,2);return!a.defaultPrevented};c.hasEventListener=function(a){var b=this._listeners,d=this._captureListeners;return!!(b&&b[a]||d&&d[a])};c.willTrigger=function(a){for(var b=this;b;){if(b.hasEventListener(a))return!0;b=b.parent}return!1};c.toString=function(){return"[EventDispatcher]"};c._dispatchEvent=function(a,c){var b,e,g=2>=c?this._captureListeners:this._listeners;if(a&&g&&(e=g[a.type])&&(b=e.length)){try{a.currentTarget=
this}catch(p){}try{a.eventPhase=c|0}catch(p){}a.removed=!1;e=e.slice();for(g=0;g<b&&!a.immediatePropagationStopped;g++){var h=e[g];h.handleEvent?h.handleEvent(a):h(a);a.removed&&(this.off(a.type,h,1==c),a.removed=!1)}}2===c&&this._dispatchEvent(a,2.1)};createjs.EventDispatcher=a})();this.createjs=this.createjs||{};
(function(){function a(){throw"Ticker cannot be instantiated.";}a.RAF_SYNCHED="synched";a.RAF="raf";a.TIMEOUT="timeout";a.timingMode=null;a.maxDelta=0;a.paused=!1;a.removeEventListener=null;a.removeAllEventListeners=null;a.dispatchEvent=null;a.hasEventListener=null;a._listeners=null;createjs.EventDispatcher.initialize(a);a._addEventListener=a.addEventListener;a.addEventListener=function(){!a._inited&&a.init();return a._addEventListener.apply(a,arguments)};a._inited=!1;a._startTime=0;a._pausedTime=
0;a._ticks=0;a._pausedTicks=0;a._interval=50;a._lastTime=0;a._times=null;a._tickTimes=null;a._timerId=null;a._raf=!0;a._setInterval=function(b){a._interval=b;a._inited&&a._setupTick()};a.setInterval=createjs.deprecate(a._setInterval,"Ticker.setInterval");a._getInterval=function(){return a._interval};a.getInterval=createjs.deprecate(a._getInterval,"Ticker.getInterval");a._setFPS=function(b){a._setInterval(1E3/b)};a.setFPS=createjs.deprecate(a._setFPS,"Ticker.setFPS");a._getFPS=function(){return 1E3/
a._interval};a.getFPS=createjs.deprecate(a._getFPS,"Ticker.getFPS");try{Object.defineProperties(a,{interval:{get:a._getInterval,set:a._setInterval},framerate:{get:a._getFPS,set:a._setFPS}})}catch(e){console.log(e)}a.init=function(){a._inited||(a._inited=!0,a._times=[],a._tickTimes=[],a._startTime=a._getTime(),a._times.push(a._lastTime=0),a.interval=a._interval)};a.reset=function(){if(a._raf){var b=window.cancelAnimationFrame||window.webkitCancelAnimationFrame||window.mozCancelAnimationFrame||window.oCancelAnimationFrame||
window.msCancelAnimationFrame;b&&b(a._timerId)}else clearTimeout(a._timerId);a.removeAllEventListeners("tick");a._timerId=a._times=a._tickTimes=null;a._startTime=a._lastTime=a._ticks=a._pausedTime=0;a._inited=!1};a.getMeasuredTickTime=function(b){var c=0,e=a._tickTimes;if(!e||1>e.length)return-1;b=Math.min(e.length,b||a._getFPS()|0);for(var g=0;g<b;g++)c+=e[g];return c/b};a.getMeasuredFPS=function(b){var c=a._times;if(!c||2>c.length)return-1;b=Math.min(c.length-1,b||a._getFPS()|0);return 1E3/((c[0]-
c[b])/b)};a.getTime=function(b){return a._startTime?a._getTime()-(b?a._pausedTime:0):-1};a.getEventTime=function(b){return a._startTime?(a._lastTime||a._startTime)-(b?a._pausedTime:0):-1};a.getTicks=function(b){return a._ticks-(b?a._pausedTicks:0)};a._handleSynch=function(){a._timerId=null;a._setupTick();a._getTime()-a._lastTime>=.97*(a._interval-1)&&a._tick()};a._handleRAF=function(){a._timerId=null;a._setupTick();a._tick()};a._handleTimeout=function(){a._timerId=null;a._setupTick();a._tick()};a._setupTick=
function(){if(null==a._timerId){var b=a.timingMode;if(b==a.RAF_SYNCHED||b==a.RAF){var c=window.requestAnimationFrame||window.webkitRequestAnimationFrame||window.mozRequestAnimationFrame||window.oRequestAnimationFrame||window.msRequestAnimationFrame;if(c){a._timerId=c(b==a.RAF?a._handleRAF:a._handleSynch);a._raf=!0;return}}a._raf=!1;a._timerId=setTimeout(a._handleTimeout,a._interval)}};a._tick=function(){var b=a.paused,c=a._getTime(),f=c-a._lastTime;a._lastTime=c;a._ticks++;b&&(a._pausedTicks++,a._pausedTime+=
f);if(a.hasEventListener("tick")){var g=new createjs.Event("tick"),h=a.maxDelta;g.delta=h&&f>h?h:f;g.paused=b;g.time=c;g.runTime=c-a._pausedTime;a.dispatchEvent(g)}for(a._tickTimes.unshift(a._getTime()-c);100<a._tickTimes.length;)a._tickTimes.pop();for(a._times.unshift(c);100<a._times.length;)a._times.pop()};var c=window,b=c.performance.now||c.performance.mozNow||c.performance.msNow||c.performance.oNow||c.performance.webkitNow;a._getTime=function(){return(b&&b.call(c.performance)||(new Date).getTime())-
a._startTime};createjs.Ticker=a})();this.createjs=this.createjs||{};
(function(){function a(a){this.EventDispatcher_constructor();this.ignoreGlobalPause=!1;this.loop=0;this.bounce=this.reversed=this.useTicks=!1;this.timeScale=1;this.position=this.duration=0;this.rawPosition=-1;this._paused=!0;this._labelList=this._labels=this._parent=this._prev=this._next=null;a&&(this.useTicks=!!a.useTicks,this.ignoreGlobalPause=!!a.ignoreGlobalPause,this.loop=!0===a.loop?-1:a.loop||0,this.reversed=!!a.reversed,this.bounce=!!a.bounce,this.timeScale=a.timeScale||1,a.onChange&&this.addEventListener("change",
a.onChange),a.onComplete&&this.addEventListener("complete",a.onComplete))}var c=createjs.extend(a,createjs.EventDispatcher);c._setPaused=function(a){createjs.Tween._register(this,a);return this};c.setPaused=createjs.deprecate(c._setPaused,"AbstractTween.setPaused");c._getPaused=function(){return this._paused};c.getPaused=createjs.deprecate(c._getPaused,"AbstactTween.getPaused");c._getCurrentLabel=function(a){var b=this.getLabels();null==a&&(a=this.position);for(var c=0,f=b.length;c<f&&!(a<b[c].position);c++);
return 0===c?null:b[c-1].label};c.getCurrentLabel=createjs.deprecate(c._getCurrentLabel,"AbstractTween.getCurrentLabel");try{Object.defineProperties(c,{paused:{set:c._setPaused,get:c._getPaused},currentLabel:{get:c._getCurrentLabel}})}catch(b){}c.advance=function(a,c){this.setPosition(this.rawPosition+a*this.timeScale,c)};c.setPosition=function(a,c,d,f){var b=this.duration,e=this.loop,p=this.rawPosition,l=0;0>a&&(a=0);if(0===b){var r=!0;if(-1!==p)return r}else{var n=a/b|0;l=a-n*b;(r=-1!==e&&a>=e*
b+b)&&(a=(l=b)*(n=e)+b);if(a===p)return r;!this.reversed!==!(this.bounce&&n%2)&&(l=b-l)}this.position=l;this.rawPosition=a;this._updatePosition(d,r);r&&(this.paused=!0);f&&f(this);c||this._runActions(p,a,d,!d&&-1===p);this.dispatchEvent("change");r&&this.dispatchEvent("complete")};c.calculatePosition=function(a){var b=this.duration,c=this.loop,f=0;if(0===b)return 0;-1!==c&&a>=c*b+b?(a=b,f=c):0>a?a=0:(f=a/b|0,a-=f*b);return!this.reversed!==!(this.bounce&&f%2)?b-a:a};c.getLabels=function(){var a=this._labelList;
if(!a){a=this._labelList=[];var c=this._labels,d;for(d in c)a.push({label:d,position:c[d]});a.sort(function(a,b){return a.position-b.position})}return a};c.setLabels=function(a){this._labels=a;this._labelList=null};c.addLabel=function(a,c){this._labels||(this._labels={});this._labels[a]=c;var b=this._labelList;if(b){for(var f=0,e=b.length;f<e&&!(c<b[f].position);f++);b.splice(f,0,{label:a,position:c})}};c.gotoAndPlay=function(a){this.paused=!1;this._goto(a)};c.gotoAndStop=function(a){this.paused=
!0;this._goto(a)};c.resolve=function(a){var b=Number(a);isNaN(b)&&(b=this._labels&&this._labels[a]);return b};c.toString=function(){return"[AbstractTween]"};c.clone=function(){throw"AbstractTween can not be cloned.";};c._init=function(a){a&&a.paused||(this.paused=!1);a&&null!=a.position&&this.setPosition(a.position)};c._updatePosition=function(a,c){};c._goto=function(a){a=this.resolve(a);null!=a&&this.setPosition(a,!1,!0)};c._runActions=function(a,c,d,f){if(this._actionHead||this.tweens){var b=this.duration,
e=this.reversed,p=this.bounce,l=this.loop,r,n,u;if(0===b){var q=r=n=u=0;e=p=!1}else q=a/b|0,r=c/b|0,n=a-q*b,u=c-r*b;-1!==l&&(r>l&&(u=b,r=l),q>l&&(n=b,q=l));if(d)return this._runActionsRange(u,u,d,f);if(q!==r||n!==u||d||f){-1===q&&(q=n=0);a=a<=c;c=q;do{l=c===q?n:a?0:b;var B=c===r?u:a?b:0;!e!==!(p&&c%2)&&(l=b-l,B=b-B);if((!p||c===q||l!==B)&&this._runActionsRange(l,B,d,f||c!==q&&!p))return!0;f=!1}while(a&&++c<=r||!a&&--c>=r)}}};c._runActionsRange=function(a,c,d,f){};createjs.AbstractTween=createjs.promote(a,
"EventDispatcher")})();this.createjs=this.createjs||{};
(function(){function a(b,f){this.AbstractTween_constructor(f);this.pluginData=null;this.target=b;this.passive=!1;this._stepTail=this._stepHead=new c(null,0,0,{},null,!0);this._stepPosition=0;this._injected=this._pluginIds=this._plugins=this._actionTail=this._actionHead=null;f&&(this.pluginData=f.pluginData,f.override&&a.removeTweens(b));this.pluginData||(this.pluginData={});this._init(f)}function c(a,b,c,e,p,l){this.next=null;this.prev=a;this.t=b;this.d=c;this.props=e;this.ease=p;this.passive=l;this.index=
a?a.index+1:0}function b(a,b,c,e,p){this.next=null;this.prev=a;this.t=b;this.d=0;this.scope=c;this.funct=e;this.params=p}var e=createjs.extend(a,createjs.AbstractTween);a.IGNORE={};a._tweens=[];a._plugins=null;a._tweenHead=null;a._tweenTail=null;a.get=function(b,c){return new a(b,c)};a.tick=function(b,c){for(var d=a._tweenHead;d;){var f=d._next;c&&!d.ignoreGlobalPause||d._paused||d.advance(d.useTicks?1:b);d=f}};a.handleEvent=function(a){"tick"===a.type&&this.tick(a.delta,a.paused)};a.removeTweens=
function(b){if(b.tweenjs_count){for(var c=a._tweenHead;c;){var d=c._next;c.target===b&&a._register(c,!0);c=d}b.tweenjs_count=0}};a.removeAllTweens=function(){for(var b=a._tweenHead;b;){var c=b._next;b._paused=!0;b.target&&(b.target.tweenjs_count=0);b._next=b._prev=null;b=c}a._tweenHead=a._tweenTail=null};a.hasActiveTweens=function(b){return b?!!b.tweenjs_count:!!a._tweenHead};a._installPlugin=function(b){for(var c=b.priority=b.priority||0,d=a._plugins=a._plugins||[],e=0,p=d.length;e<p&&!(c<d[e].priority);e++);
d.splice(e,0,b)};a._register=function(b,c){var d=b.target;if(!c&&b._paused)d&&(d.tweenjs_count=d.tweenjs_count?d.tweenjs_count+1:1),(d=a._tweenTail)?(a._tweenTail=d._next=b,b._prev=d):a._tweenHead=a._tweenTail=b,!a._inited&&createjs.Ticker&&(createjs.Ticker.addEventListener("tick",a),a._inited=!0);else if(c&&!b._paused){d&&d.tweenjs_count--;d=b._next;var f=b._prev;d?d._prev=f:a._tweenTail=f;f?f._next=d:a._tweenHead=d;b._next=b._prev=null}b._paused=c};e.wait=function(a,b){0<a&&this._addStep(+a,this._stepTail.props,
null,b);return this};e.to=function(a,b,c){if(null==b||0>b)b=0;b=this._addStep(+b,null,c);this._appendProps(a,b);return this};e.label=function(a){this.addLabel(a,this.duration);return this};e.call=function(a,b,c){return this._addAction(c||this.target,a,b||[this])};e.set=function(a,b){return this._addAction(b||this.target,this._set,[a])};e.play=function(a){return this._addAction(a||this,this._set,[{paused:!1}])};e.pause=function(a){return this._addAction(a||this,this._set,[{paused:!0}])};e.w=e.wait;
e.t=e.to;e.c=e.call;e.s=e.set;e.toString=function(){return"[Tween]"};e.clone=function(){throw"Tween can not be cloned.";};e._addPlugin=function(a){var b=this._pluginIds||(this._pluginIds={}),c=a.ID;if(c&&!b[c]){b[c]=!0;b=this._plugins||(this._plugins=[]);c=a.priority||0;for(var d=0,e=b.length;d<e;d++)if(c<b[d].priority){b.splice(d,0,a);return}b.push(a)}};e._updatePosition=function(a,b){var c=this._stepHead.next,d=this.position,e=this.duration;if(this.target&&c){for(var f=c.next;f&&f.t<=d;)c=c.next,
f=c.next;this._updateTargetProps(c,b?0===e?1:d/e:(d-c.t)/c.d,b)}this._stepPosition=c?d-c.t:0};e._updateTargetProps=function(b,c,e){if(!(this.passive=!!b.passive)){var d,f=b.prev.props,g=b.props;if(d=b.ease)c=d(c,0,1,1);d=this._plugins;var r;a:for(r in f){var n=f[r];var u=g[r];n=n!==u&&"number"===typeof n?n+(u-n)*c:1<=c?u:n;if(d){u=0;for(var q=d.length;u<q;u++){var B=d[u].change(this,b,r,n,c,e);if(B===a.IGNORE)continue a;void 0!==B&&(n=B)}}this.target[r]=n}}};e._runActionsRange=function(a,b,c,e){var d=
(c=a>b)?this._actionTail:this._actionHead,f=b,g=a;c&&(f=a,g=b);for(var h=this.position;d;){var u=d.t;if(u===b||u>g&&u<f||e&&u===a)if(d.funct.apply(d.scope,d.params),h!==this.position)return!0;d=c?d.prev:d.next}};e._appendProps=function(b,c,e){var d=this._stepHead.props,f=this.target,g=a._plugins,r,n,u=c.prev,q=u.props,B=c.props||(c.props=this._cloneProps(q)),m={};for(r in b)if(b.hasOwnProperty(r)&&(m[r]=B[r]=b[r],void 0===d[r])){var t=void 0;if(g)for(n=g.length-1;0<=n;n--){var w=g[n].init(this,r,
t);void 0!==w&&(t=w);if(t===a.IGNORE){delete B[r];delete m[r];break}}t!==a.IGNORE&&(void 0===t&&(t=f[r]),q[r]=void 0===t?null:t)}for(r in m){var z;for(b=u;(z=b)&&(b=z.prev);)if(b.props!==z.props){if(void 0!==b.props[r])break;b.props[r]=q[r]}}if(!1!==e&&(g=this._plugins))for(n=g.length-1;0<=n;n--)g[n].step(this,c,m);if(e=this._injected)this._injected=null,this._appendProps(e,c,!1)};e._injectProp=function(a,b){(this._injected||(this._injected={}))[a]=b};e._addStep=function(a,b,e,h){b=new c(this._stepTail,
this.duration,a,b,e,h||!1);this.duration+=a;return this._stepTail=this._stepTail.next=b};e._addAction=function(a,c,e){a=new b(this._actionTail,this.duration,a,c,e);this._actionTail?this._actionTail.next=a:this._actionHead=a;this._actionTail=a;return this};e._set=function(a){for(var b in a)this[b]=a[b]};e._cloneProps=function(a){var b={},c;for(c in a)b[c]=a[c];return b};createjs.Tween=createjs.promote(a,"AbstractTween")})();this.createjs=this.createjs||{};
(function(){function a(a){if(a instanceof Array||null==a&&1<arguments.length){var b=a;var c=arguments[1];a=arguments[2]}else a&&(b=a.tweens,c=a.labels);this.AbstractTween_constructor(a);this.tweens=[];b&&this.addTween.apply(this,b);this.setLabels(c);this._init(a)}var c=createjs.extend(a,createjs.AbstractTween);c.addTween=function(a){a._parent&&a._parent.removeTween(a);var b=arguments.length;if(1<b){for(var c=0;c<b;c++)this.addTween(arguments[c]);return arguments[b-1]}if(0===b)return null;this.tweens.push(a);
a._parent=this;a.paused=!0;b=a.duration;0<a.loop&&(b*=a.loop+1);b>this.duration&&(this.duration=b);0<=this.rawPosition&&a.setPosition(this.rawPosition);return a};c.removeTween=function(a){var b=arguments.length;if(1<b){for(var c=!0,f=0;f<b;f++)c=c&&this.removeTween(arguments[f]);return c}if(0===b)return!0;b=this.tweens;for(f=b.length;f--;)if(b[f]===a)return b.splice(f,1),a._parent=null,a.duration>=this.duration&&this.updateDuration(),!0;return!1};c.updateDuration=function(){for(var a=this.duration=
0,c=this.tweens.length;a<c;a++){var d=this.tweens[a],f=d.duration;0<d.loop&&(f*=d.loop+1);f>this.duration&&(this.duration=f)}};c.toString=function(){return"[Timeline]"};c.clone=function(){throw"Timeline can not be cloned.";};c._updatePosition=function(a,c){for(var b=this.position,e=0,g=this.tweens.length;e<g;e++)this.tweens[e].setPosition(b,!0,a)};c._runActionsRange=function(a,c,d,f){for(var b=this.position,e=0,p=this.tweens.length;e<p;e++)if(this.tweens[e]._runActions(a,c,d,f),b!==this.position)return!0};
createjs.Timeline=createjs.promote(a,"AbstractTween")})();this.createjs=this.createjs||{};
(function(){function a(){throw"Ease cannot be instantiated.";}a.linear=function(a){return a};a.none=a.linear;a.get=function(a){-1>a?a=-1:1<a&&(a=1);return function(b){return 0==a?b:0>a?b*(b*-a+1+a):b*((2-b)*a+(1-a))}};a.getPowIn=function(a){return function(b){return Math.pow(b,a)}};a.getPowOut=function(a){return function(b){return 1-Math.pow(1-b,a)}};a.getPowInOut=function(a){return function(b){return 1>(b*=2)?.5*Math.pow(b,a):1-.5*Math.abs(Math.pow(2-b,a))}};a.quadIn=a.getPowIn(2);a.quadOut=a.getPowOut(2);
a.quadInOut=a.getPowInOut(2);a.cubicIn=a.getPowIn(3);a.cubicOut=a.getPowOut(3);a.cubicInOut=a.getPowInOut(3);a.quartIn=a.getPowIn(4);a.quartOut=a.getPowOut(4);a.quartInOut=a.getPowInOut(4);a.quintIn=a.getPowIn(5);a.quintOut=a.getPowOut(5);a.quintInOut=a.getPowInOut(5);a.sineIn=function(a){return 1-Math.cos(a*Math.PI/2)};a.sineOut=function(a){return Math.sin(a*Math.PI/2)};a.sineInOut=function(a){return-.5*(Math.cos(Math.PI*a)-1)};a.getBackIn=function(a){return function(b){return b*b*((a+1)*b-a)}};
a.backIn=a.getBackIn(1.7);a.getBackOut=function(a){return function(b){return--b*b*((a+1)*b+a)+1}};a.backOut=a.getBackOut(1.7);a.getBackInOut=function(a){a*=1.525;return function(b){return 1>(b*=2)?.5*b*b*((a+1)*b-a):.5*((b-=2)*b*((a+1)*b+a)+2)}};a.backInOut=a.getBackInOut(1.7);a.circIn=function(a){return-(Math.sqrt(1-a*a)-1)};a.circOut=function(a){return Math.sqrt(1- --a*a)};a.circInOut=function(a){return 1>(a*=2)?-.5*(Math.sqrt(1-a*a)-1):.5*(Math.sqrt(1-(a-=2)*a)+1)};a.bounceIn=function(c){return 1-
a.bounceOut(1-c)};a.bounceOut=function(a){return a<1/2.75?7.5625*a*a:a<2/2.75?7.5625*(a-=1.5/2.75)*a+.75:a<2.5/2.75?7.5625*(a-=2.25/2.75)*a+.9375:7.5625*(a-=2.625/2.75)*a+.984375};a.bounceInOut=function(c){return.5>c?.5*a.bounceIn(2*c):.5*a.bounceOut(2*c-1)+.5};a.getElasticIn=function(a,b){var c=2*Math.PI;return function(d){if(0==d||1==d)return d;var e=b/c*Math.asin(1/a);return-(a*Math.pow(2,10*--d)*Math.sin((d-e)*c/b))}};a.elasticIn=a.getElasticIn(1,.3);a.getElasticOut=function(a,b){var c=2*Math.PI;
return function(d){return 0==d||1==d?d:a*Math.pow(2,-10*d)*Math.sin((d-b/c*Math.asin(1/a))*c/b)+1}};a.elasticOut=a.getElasticOut(1,.3);a.getElasticInOut=function(a,b){var c=2*Math.PI;return function(d){var e=b/c*Math.asin(1/a);return 1>(d*=2)?-.5*a*Math.pow(2,10*--d)*Math.sin((d-e)*c/b):a*Math.pow(2,-10*--d)*Math.sin((d-e)*c/b)*.5+1}};a.elasticInOut=a.getElasticInOut(1,.3*1.5);createjs.Ease=a})();this.createjs=this.createjs||{};
(function(){function a(){throw"MotionGuidePlugin cannot be instantiated.";}a.priority=0;a.ID="MotionGuide";a.install=function(){createjs.Tween._installPlugin(a);return createjs.Tween.IGNORE};a.init=function(c,b,e){"guide"==b&&c._addPlugin(a)};a.step=function(c,b,e){for(var d in e)if("guide"===d){var f=b.props.guide,g=a._solveGuideData(e.guide,f);f.valid=!g;var h=f.endData;c._injectProp("x",h.x);c._injectProp("y",h.y);if(g||!f.orient)break;f.startOffsetRot=(void 0===b.prev.props.rotation?c.target.rotation||
0:b.prev.props.rotation)-f.startData.rotation;if("fixed"==f.orient)f.endAbsRot=h.rotation+f.startOffsetRot,f.deltaRotation=0;else{g=void 0===e.rotation?c.target.rotation||0:e.rotation;h=g-f.endData.rotation-f.startOffsetRot;var p=h%360;f.endAbsRot=g;switch(f.orient){case "auto":f.deltaRotation=h;break;case "cw":f.deltaRotation=(p+360)%360+360*Math.abs(h/360|0);break;case "ccw":f.deltaRotation=(p-360)%360+-360*Math.abs(h/360|0)}}c._injectProp("rotation",f.endAbsRot)}};a.change=function(c,b,e,d,f,g){if((d=
b.props.guide)&&b.props!==b.prev.props&&d!==b.prev.props.guide){if("guide"===e&&!d.valid||"x"==e||"y"==e||"rotation"===e&&d.orient)return createjs.Tween.IGNORE;a._ratioToPositionData(f,d,c.target)}};a.debug=function(c,b,e){c=c.guide||c;var d=a._findPathProblems(c);d&&console.error("MotionGuidePlugin Error found: \n"+d);if(!b)return d;var f,g=c.path,h=g.length;b.save();b.lineCap="round";b.lineJoin="miter";b.beginPath();b.moveTo(g[0],g[1]);for(f=2;f<h;f+=4)b.quadraticCurveTo(g[f],g[f+1],g[f+2],g[f+
3]);b.strokeStyle="black";b.lineWidth=4.5;b.stroke();b.strokeStyle="white";b.lineWidth=3;b.stroke();b.closePath();g=e.length;if(e&&g){h={};var p={};a._solveGuideData(c,h);for(f=0;f<g;f++)h.orient="fixed",a._ratioToPositionData(e[f],h,p),b.beginPath(),b.moveTo(p.x,p.y),b.lineTo(p.x+9*Math.cos(.0174533*p.rotation),p.y+9*Math.sin(.0174533*p.rotation)),b.strokeStyle="black",b.lineWidth=4.5,b.stroke(),b.strokeStyle="red",b.lineWidth=3,b.stroke(),b.closePath()}b.restore();return d};a._solveGuideData=function(c,
b){var e;if(e=a.debug(c))return e;var d=b.path=c.path;b.orient=c.orient;b.subLines=[];b.totalLength=0;b.startOffsetRot=0;b.deltaRotation=0;b.startData={ratio:0};b.endData={ratio:1};b.animSpan=1;var f=d.length,g,h={};var p=d[0];var l=d[1];for(e=2;e<f;e+=4){var r=d[e];var n=d[e+1];var u=d[e+2];var q=d[e+3];var B={weightings:[],estLength:0,portion:0},m=p;var t=l;for(g=1;10>=g;g++)a._getParamsForCurve(p,l,r,n,u,q,g/10,!1,h),m=h.x-m,t=h.y-t,t=Math.sqrt(m*m+t*t),B.weightings.push(t),B.estLength+=t,m=h.x,
t=h.y;b.totalLength+=B.estLength;for(g=0;10>g;g++)t=B.estLength,B.weightings[g]/=t;b.subLines.push(B);p=u;l=q}t=b.totalLength;d=b.subLines.length;for(e=0;e<d;e++)b.subLines[e].portion=b.subLines[e].estLength/t;e=isNaN(c.start)?0:c.start;d=isNaN(c.end)?1:c.end;a._ratioToPositionData(e,b,b.startData);a._ratioToPositionData(d,b,b.endData);b.startData.ratio=e;b.endData.ratio=d;b.animSpan=b.endData.ratio-b.startData.ratio};a._ratioToPositionData=function(c,b,e){var d=b.subLines,f,g=0,h=c*b.animSpan+b.startData.ratio;
var p=d.length;for(f=0;f<p;f++){var l=d[f].portion;if(g+l>=h){var r=f;break}g+=l}void 0===r&&(r=p-1,g-=l);d=d[r].weightings;var n=l;p=d.length;for(f=0;f<p;f++){l=d[f]*n;if(g+l>=h)break;g+=l}r=4*r+2;p=b.path;a._getParamsForCurve(p[r-2],p[r-1],p[r],p[r+1],p[r+2],p[r+3],f/10+(h-g)/l*.1,b.orient,e);b.orient&&(e.rotation=.99999<=c&&1.00001>=c&&void 0!==b.endAbsRot?b.endAbsRot:e.rotation+(b.startOffsetRot+c*b.deltaRotation));return e};a._getParamsForCurve=function(a,b,e,d,f,g,h,p,l){var c=1-h;l.x=c*c*a+
2*c*h*e+h*h*f;l.y=c*c*b+2*c*h*d+h*h*g;p&&(l.rotation=57.2957795*Math.atan2((d-b)*c+(g-d)*h,(e-a)*c+(f-e)*h))};a._findPathProblems=function(a){var b=a.path,c=b&&b.length||0;if(6>c||(c-2)%4)return"\tCannot parse 'path' array due to invalid number of entries in path. There should be an odd number of points, at least 3 points, and 2 entries per point (x & y). See 'CanvasRenderingContext2D.quadraticCurveTo' for details as 'path' models a quadratic bezier.\n\nOnly [ "+(c+" ] values found. Expected: "+Math.max(4*
Math.ceil((c-2)/4)+2,6));for(var d=0;d<c;d++)if(isNaN(b[d]))return"All data in path array must be numeric";b=a.start;if(isNaN(b)&&void 0!==b)return"'start' out of bounds. Expected 0 to 1, got: "+b;b=a.end;if(isNaN(b)&&void 0!==b)return"'end' out of bounds. Expected 0 to 1, got: "+b;if((a=a.orient)&&"fixed"!=a&&"auto"!=a&&"cw"!=a&&"ccw"!=a)return'Invalid orientation value. Expected ["fixed", "auto", "cw", "ccw", undefined], got: '+a};createjs.MotionGuidePlugin=a})();this.createjs=this.createjs||{};
(function(){var a=createjs.TweenJS=createjs.TweenJS||{};a.version="1.0.0";a.buildDate="Thu, 14 Sep 2017 19:47:47 GMT"})();
(function(){function a(a){a=String(a);return a.charAt(0).toUpperCase()+a.slice(1)}function c(a,b){var c=-1,d=a?a.length:0;if("number"==typeof d&&-1<d&&d<=q)for(;++c<d;)b(a[c],c,a);else e(a,b)}function b(b){b=String(b).replace(/^ +| +$/g,"");return/^(?:webOS|i(?:OS|P))/.test(b)?b:a(b)}function e(a,b){for(var c in a)m.call(a,c)&&b(a[c],c,a)}function d(b){return null==b?a(b):t.call(b).slice(8,-1)}function f(a,b){var c=null!=a?typeof a[b]:"number";return!/^(?:boolean|number|string|undefined)$/.test(c)&&
("object"==c?!!a[b]:!0)}function g(a){return String(a).replace(/([ -])(?!$)/g,"$1?")}function h(a,b){var d=null;c(a,function(c,e){d=b(d,c,e,a)});return d}function p(a){function c(c){return h(c,function(c,d){var e=d.pattern||g(d);!c&&(c=RegExp("\\b"+e+" *\\d+[.\\w_]*","i").exec(a)||RegExp("\\b"+e+" *\\w+-[\\w]*","i").exec(a)||RegExp("\\b"+e+"(?:; *(?:[a-z]+[_-])?[a-z]+\\d+|[^ ();-]*)","i").exec(a))&&((c=String(d.label&&!RegExp(e,"i").test(d.label)?d.label:c).split("/"))[1]&&!/[\d.]+/.test(c[0])&&(c[0]+=
" "+c[1]),d=d.label||d,c=b(c[0].replace(RegExp(e,"i"),d).replace(RegExp("; *(?:"+d+"[_-])?","i")," ").replace(RegExp("("+d+")[-_.]?(\\w)","i"),"$1 $2")));return c})}function l(b){return h(b,function(b,c){return b||(RegExp(c+"(?:-[\\d.]+/|(?: for [\\w-]+)?[ /-])([\\d.]+[^ ();/_-]*)","i").exec(a)||0)[1]||null})}var m=r,n=a&&"object"==typeof a&&"String"!=d(a);n&&(m=a,a=null);var q=m.navigator||{},y=q.userAgent||"";a||(a=y);var u=n?!!q.likeChrome:/\bChrome\b/.test(a)&&!/internal|\n/i.test(t.toString()),
w=n?"Object":"ScriptBridgingProxyObject",z=n?"Object":"Environment",A=n&&m.java?"JavaPackage":d(m.java),H=n?"Object":"RuntimeObject";z=(A=/\bJava/.test(A)&&m.java)&&d(m.environment)==z;var W=A?"a":"\u03b1",X=A?"b":"\u03b2",S=m.document||{},K=m.operamini||m.opera,P=B.test(P=n&&K?K["[[Class]]"]:d(K))?P:K=null,k,Q=a;n=[];var R=null,L=a==y;y=L&&K&&"function"==typeof K.version&&K.version();var C=function(b){return h(b,function(b,c){return b||RegExp("\\b"+(c.pattern||g(c))+"\\b","i").exec(a)&&(c.label||
c)})}([{label:"EdgeHTML",pattern:"Edge"},"Trident",{label:"WebKit",pattern:"AppleWebKit"},"iCab","Presto","NetFront","Tasman","KHTML","Gecko"]),v=function(b){return h(b,function(b,c){return b||RegExp("\\b"+(c.pattern||g(c))+"\\b","i").exec(a)&&(c.label||c)})}(["Adobe AIR","Arora","Avant Browser","Breach","Camino","Electron","Epiphany","Fennec","Flock","Galeon","GreenBrowser","iCab","Iceweasel","K-Meleon","Konqueror","Lunascape","Maxthon",{label:"Microsoft Edge",pattern:"Edge"},"Midori","Nook Browser",
"PaleMoon","PhantomJS","Raven","Rekonq","RockMelt",{label:"Samsung Internet",pattern:"SamsungBrowser"},"SeaMonkey",{label:"Silk",pattern:"(?:Cloud9|Silk-Accelerated)"},"Sleipnir","SlimBrowser",{label:"SRWare Iron",pattern:"Iron"},"Sunrise","Swiftfox","Waterfox","WebPositive","Opera Mini",{label:"Opera Mini",pattern:"OPiOS"},"Opera",{label:"Opera",pattern:"OPR"},"Chrome",{label:"Chrome Mobile",pattern:"(?:CriOS|CrMo)"},{label:"Firefox",pattern:"(?:Firefox|Minefield)"},{label:"Firefox for iOS",pattern:"FxiOS"},
{label:"IE",pattern:"IEMobile"},{label:"IE",pattern:"MSIE"},"Safari"]),D=c([{label:"BlackBerry",pattern:"BB10"},"BlackBerry",{label:"Galaxy S",pattern:"GT-I9000"},{label:"Galaxy S2",pattern:"GT-I9100"},{label:"Galaxy S3",pattern:"GT-I9300"},{label:"Galaxy S4",pattern:"GT-I9500"},{label:"Galaxy S5",pattern:"SM-G900"},{label:"Galaxy S6",pattern:"SM-G920"},{label:"Galaxy S6 Edge",pattern:"SM-G925"},{label:"Galaxy S7",pattern:"SM-G930"},{label:"Galaxy S7 Edge",pattern:"SM-G935"},"Google TV","Lumia","iPad",
"iPod","iPhone","Kindle",{label:"Kindle Fire",pattern:"(?:Cloud9|Silk-Accelerated)"},"Nexus","Nook","PlayBook","PlayStation Vita","PlayStation","TouchPad","Transformer",{label:"Wii U",pattern:"WiiU"},"Wii","Xbox One",{label:"Xbox 360",pattern:"Xbox"},"Xoom"]),F=function(b){return h(b,function(b,c,d){return b||(c[D]||c[/^[a-z]+(?: +[a-z]+\b)*/i.exec(D)]||RegExp("\\b"+g(d)+"(?:\\b|\\w*\\d)","i").exec(a))&&d})}({Apple:{iPad:1,iPhone:1,iPod:1},Archos:{},Amazon:{Kindle:1,"Kindle Fire":1},Asus:{Transformer:1},
"Barnes & Noble":{Nook:1},BlackBerry:{PlayBook:1},Google:{"Google TV":1,Nexus:1},HP:{TouchPad:1},HTC:{},LG:{},Microsoft:{Xbox:1,"Xbox One":1},Motorola:{Xoom:1},Nintendo:{"Wii U":1,Wii:1},Nokia:{Lumia:1},Samsung:{"Galaxy S":1,"Galaxy S2":1,"Galaxy S3":1,"Galaxy S4":1},Sony:{PlayStation:1,"PlayStation Vita":1}}),x=function(c){return h(c,function(c,d){var e=d.pattern||g(d);if(!c&&(c=RegExp("\\b"+e+"(?:/[\\d.]+|[ \\w.]*)","i").exec(a))){var f=c,h=d.label||d,l={"10.0":"10","6.4":"10 Technical Preview",
"6.3":"8.1","6.2":"8","6.1":"Server 2008 R2 / 7","6.0":"Server 2008 / Vista","5.2":"Server 2003 / XP 64-bit","5.1":"XP","5.01":"2000 SP1","5.0":"2000","4.0":"NT","4.90":"ME"};e&&h&&/^Win/i.test(f)&&!/^Windows Phone /i.test(f)&&(l=l[/[\d.]+$/.exec(f)])&&(f="Windows "+l);f=String(f);e&&h&&(f=f.replace(RegExp(e,"i"),h));c=f=b(f.replace(/ ce$/i," CE").replace(/\bhpw/i,"web").replace(/\bMacintosh\b/,"Mac OS").replace(/_PowerPC\b/i," OS").replace(/\b(OS X) [^ \d]+/i,"$1").replace(/\bMac (OS X)\b/,"$1").replace(/\/(\d)/,
" $1").replace(/_/g,".").replace(/(?: BePC|[ .]*fc[ \d.]+)$/i,"").replace(/\bx86\.64\b/gi,"x86_64").replace(/\b(Windows Phone) OS\b/,"$1").replace(/\b(Chrome OS \w+) [\d.]+\b/,"$1").split(" on ")[0])}return c})}(["Windows Phone","Android","CentOS",{label:"Chrome OS",pattern:"CrOS"},"Debian","Fedora","FreeBSD","Gentoo","Haiku","Kubuntu","Linux Mint","OpenBSD","Red Hat","SuSE","Ubuntu","Xubuntu","Cygwin","Symbian OS","hpwOS","webOS ","webOS","Tablet OS","Tizen","Linux","Mac OS X","Macintosh","Mac",
"Windows 98;","Windows "]);C&&(C=[C]);F&&!D&&(D=c([F]));if(k=/\bGoogle TV\b/.exec(D))D=k[0];/\bSimulator\b/i.test(a)&&(D=(D?D+" ":"")+"Simulator");"Opera Mini"==v&&/\bOPiOS\b/.test(a)&&n.push("running in Turbo/Uncompressed mode");"IE"==v&&/\blike iPhone OS\b/.test(a)?(k=p(a.replace(/like iPhone OS/,"")),F=k.manufacturer,D=k.product):/^iP/.test(D)?(v||(v="Safari"),x="iOS"+((k=/ OS ([\d_]+)/i.exec(a))?" "+k[1].replace(/_/g,"."):"")):"Konqueror"!=v||/buntu/i.test(x)?F&&"Google"!=F&&(/Chrome/.test(v)&&
!/\bMobile Safari\b/i.test(a)||/\bVita\b/.test(D))||/\bAndroid\b/.test(x)&&/^Chrome/.test(v)&&/\bVersion\//i.test(a)?(v="Android Browser",x=/\bAndroid\b/.test(x)?x:"Android"):"Silk"==v?(/\bMobi/i.test(a)||(x="Android",n.unshift("desktop mode")),/Accelerated *= *true/i.test(a)&&n.unshift("accelerated")):"PaleMoon"==v&&(k=/\bFirefox\/([\d.]+)\b/.exec(a))?n.push("identifying as Firefox "+k[1]):"Firefox"==v&&(k=/\b(Mobile|Tablet|TV)\b/i.exec(a))?(x||(x="Firefox OS"),D||(D=k[1])):!v||(k=!/\bMinefield\b/i.test(a)&&
/\b(?:Firefox|Safari)\b/.exec(v))?(v&&!D&&/[\/,]|^[^(]+?\)/.test(a.slice(a.indexOf(k+"/")+8))&&(v=null),(k=D||F||x)&&(D||F||/\b(?:Android|Symbian OS|Tablet OS|webOS)\b/.test(x))&&(v=/[a-z]+(?: Hat)?/i.exec(/\bAndroid\b/.test(x)?x:k)+" Browser")):"Electron"==v&&(k=(/\bChrome\/([\d.]+)\b/.exec(a)||0)[1])&&n.push("Chromium "+k):x="Kubuntu";y||(y=l(["(?:Cloud9|CriOS|CrMo|Edge|FxiOS|IEMobile|Iron|Opera ?Mini|OPiOS|OPR|Raven|SamsungBrowser|Silk(?!/[\\d.]+$))","Version",g(v),"(?:Firefox|Minefield|NetFront)"]));
if(k="iCab"==C&&3<parseFloat(y)&&"WebKit"||/\bOpera\b/.test(v)&&(/\bOPR\b/.test(a)?"Blink":"Presto")||/\b(?:Midori|Nook|Safari)\b/i.test(a)&&!/^(?:Trident|EdgeHTML)$/.test(C)&&"WebKit"||!C&&/\bMSIE\b/i.test(a)&&("Mac OS"==x?"Tasman":"Trident")||"WebKit"==C&&/\bPlayStation\b(?! Vita\b)/i.test(v)&&"NetFront")C=[k];"IE"==v&&(k=(/; *(?:XBLWP|ZuneWP)(\d+)/i.exec(a)||0)[1])?(v+=" Mobile",x="Windows Phone "+(/\+$/.test(k)?k:k+".x"),n.unshift("desktop mode")):/\bWPDesktop\b/i.test(a)?(v="IE Mobile",x="Windows Phone 8.x",
n.unshift("desktop mode"),y||(y=(/\brv:([\d.]+)/.exec(a)||0)[1])):"IE"!=v&&"Trident"==C&&(k=/\brv:([\d.]+)/.exec(a))&&(v&&n.push("identifying as "+v+(y?" "+y:"")),v="IE",y=k[1]);if(L){if(f(m,"global"))if(A&&(k=A.lang.System,Q=k.getProperty("os.arch"),x=x||k.getProperty("os.name")+" "+k.getProperty("os.version")),z){try{y=m.require("ringo/engine").version.join("."),v="RingoJS"}catch(V){(k=m.system)&&k.global.system==m.system&&(v="Narwhal",x||(x=k[0].os||null))}v||(v="Rhino")}else"object"==typeof m.process&&
!m.process.browser&&(k=m.process)&&("object"==typeof k.versions&&("string"==typeof k.versions.electron?(n.push("Node "+k.versions.node),v="Electron",y=k.versions.electron):"string"==typeof k.versions.nw&&(n.push("Chromium "+y,"Node "+k.versions.node),v="NW.js",y=k.versions.nw)),v||(v="Node.js",Q=k.arch,x=k.platform,y=(y=/[\d.]+/.exec(k.version))?y[0]:null));else d(k=m.runtime)==w?(v="Adobe AIR",x=k.flash.system.Capabilities.os):d(k=m.phantom)==H?(v="PhantomJS",y=(k=k.version||null)&&k.major+"."+k.minor+
"."+k.patch):"number"==typeof S.documentMode&&(k=/\bTrident\/(\d+)/i.exec(a))?(y=[y,S.documentMode],(k=+k[1]+4)!=y[1]&&(n.push("IE "+y[1]+" mode"),C&&(C[1]=""),y[1]=k),y="IE"==v?String(y[1].toFixed(1)):y[0]):"number"==typeof S.documentMode&&/^(?:Chrome|Firefox)\b/.test(v)&&(n.push("masking as "+v+" "+y),v="IE",y="11.0",C=["Trident"],x="Windows");x=x&&b(x)}y&&(k=/(?:[ab]|dp|pre|[ab]\d+pre)(?:\d+\+?)?$/i.exec(y)||/(?:alpha|beta)(?: ?\d)?/i.exec(a+";"+(L&&q.appMinorVersion))||/\bMinefield\b/i.test(a)&&
"a")&&(R=/b/i.test(k)?"beta":"alpha",y=y.replace(RegExp(k+"\\+?$"),"")+("beta"==R?X:W)+(/\d+\+?/.exec(k)||""));if("Fennec"==v||"Firefox"==v&&/\b(?:Android|Firefox OS)\b/.test(x))v="Firefox Mobile";else if("Maxthon"==v&&y)y=y.replace(/\.[\d.]+/,".x");else if(/\bXbox\b/i.test(D))"Xbox 360"==D&&(x=null),"Xbox 360"==D&&/\bIEMobile\b/.test(a)&&n.unshift("mobile mode");else if(!/^(?:Chrome|IE|Opera)$/.test(v)&&(!v||D||/Browser|Mobi/.test(v))||"Windows CE"!=x&&!/Mobi/i.test(a))if("IE"==v&&L)try{null===m.external&&
n.unshift("platform preview")}catch(V){n.unshift("embedded")}else(/\bBlackBerry\b/.test(D)||/\bBB10\b/.test(a))&&(k=(RegExp(D.replace(/ +/g," *")+"/([.\\d]+)","i").exec(a)||0)[1]||y)?(k=[k,/BB10/.test(a)],x=(k[1]?(D=null,F="BlackBerry"):"Device Software")+" "+k[0],y=null):this!=e&&"Wii"!=D&&(L&&K||/Opera/.test(v)&&/\b(?:MSIE|Firefox)\b/i.test(a)||"Firefox"==v&&/\bOS X (?:\d+\.){2,}/.test(x)||"IE"==v&&(x&&!/^Win/.test(x)&&5.5<y||/\bWindows XP\b/.test(x)&&8<y||8==y&&!/\bTrident\b/.test(a)))&&!B.test(k=
p.call(e,a.replace(B,"")+";"))&&k.name&&(k="ing as "+k.name+((k=k.version)?" "+k:""),B.test(v)?(/\bIE\b/.test(k)&&"Mac OS"==x&&(x=null),k="identify"+k):(k="mask"+k,v=P?b(P.replace(/([a-z])([A-Z])/g,"$1 $2")):"Opera",/\bIE\b/.test(k)&&(x=null),L||(y=null)),C=["Presto"],n.push(k));else v+=" Mobile";if(k=(/\bAppleWebKit\/([\d.]+\+?)/i.exec(a)||0)[1]){k=[parseFloat(k.replace(/\.(\d)$/,".0$1")),k];if("Safari"==v&&"+"==k[1].slice(-1))v="WebKit Nightly",R="alpha",y=k[1].slice(0,-1);else if(y==k[1]||y==(k[2]=
(/\bSafari\/([\d.]+\+?)/i.exec(a)||0)[1]))y=null;k[1]=(/\bChrome\/([\d.]+)/i.exec(a)||0)[1];537.36==k[0]&&537.36==k[2]&&28<=parseFloat(k[1])&&"WebKit"==C&&(C=["Blink"]);L&&(u||k[1])?(C&&(C[1]="like Chrome"),k=k[1]||(k=k[0],530>k?1:532>k?2:532.05>k?3:533>k?4:534.03>k?5:534.07>k?6:534.1>k?7:534.13>k?8:534.16>k?9:534.24>k?10:534.3>k?11:535.01>k?12:535.02>k?"13+":535.07>k?15:535.11>k?16:535.19>k?17:536.05>k?18:536.1>k?19:537.01>k?20:537.11>k?"21+":537.13>k?23:537.18>k?24:537.24>k?25:537.36>k?26:"Blink"!=
C?"27":"28")):(C&&(C[1]="like Safari"),k=(k=k[0],400>k?1:500>k?2:526>k?3:533>k?4:534>k?"4+":535>k?5:537>k?6:538>k?7:601>k?8:"8"));C&&(C[1]+=" "+(k+="number"==typeof k?".x":/[.+]/.test(k)?"":"+"));"Safari"==v&&(!y||45<parseInt(y))&&(y=k)}"Opera"==v&&(k=/\bzbov|zvav$/.exec(x))?(v+=" ",n.unshift("desktop mode"),"zvav"==k?(v+="Mini",y=null):v+="Mobile",x=x.replace(RegExp(" *"+k+"$"),"")):"Safari"==v&&/\bChrome\b/.exec(C&&C[1])&&(n.unshift("desktop mode"),v="Chrome Mobile",y=null,/\bOS X\b/.test(x)?(F=
"Apple",x="iOS 4.3+"):x=null);y&&0==y.indexOf(k=/[\d.]+$/.exec(x))&&-1<a.indexOf("/"+k+"-")&&(x=String(x.replace(k,"")).replace(/^ +| +$/g,""));C&&!/\b(?:Avant|Nook)\b/.test(v)&&(/Browser|Lunascape|Maxthon/.test(v)||"Safari"!=v&&/^iOS/.test(x)&&/\bSafari\b/.test(C[1])||/^(?:Adobe|Arora|Breach|Midori|Opera|Phantom|Rekonq|Rock|Samsung Internet|Sleipnir|Web)/.test(v)&&C[1])&&(k=C[C.length-1])&&n.push(k);n.length&&(n=["("+n.join("; ")+")"]);F&&D&&0>D.indexOf(F)&&n.push("on "+F);D&&n.push((/^on /.test(n[n.length-
1])?"":"on ")+D);if(x){var U=(k=/ ([\d.+]+)$/.exec(x))&&"/"==x.charAt(x.length-k[0].length-1);x={architecture:32,family:k&&!U?x.replace(k[0],""):x,version:k?k[1]:null,toString:function(){var a=this.version;return this.family+(a&&!U?" "+a:"")+(64==this.architecture?" 64-bit":"")}}}(k=/\b(?:AMD|IA|Win|WOW|x86_|x)64\b/i.exec(Q))&&!/\bi686\b/i.test(Q)?(x&&(x.architecture=64,x.family=x.family.replace(RegExp(" *"+k),"")),v&&(/\bWOW64\b/i.test(a)||L&&/\w(?:86|32)$/.test(q.cpuClass||q.platform)&&!/\bWin64; x64\b/i.test(a))&&
n.unshift("32-bit")):x&&/^OS X/.test(x.family)&&"Chrome"==v&&39<=parseFloat(y)&&(x.architecture=64);a||(a=null);m={};m.description=a;m.layout=C&&C[0];m.manufacturer=F;m.name=v;m.prerelease=R;m.product=D;m.ua=a;m.version=v&&y;m.os=x||{architecture:null,family:null,version:null,toString:function(){return"null"}};m.parse=p;m.toString=function(){return this.description||""};m.version&&n.unshift(y);m.name&&n.unshift(v);x&&v&&(x!=String(x).split(" ")[0]||x!=v.split(" ")[0]&&!D)&&n.push(D?"("+x+")":"on "+
x);n.length&&(m.description=n.join(" "));return m}var l={"function":!0,object:!0},r=l[typeof window]&&window||this,n=l[typeof exports]&&exports;l=l[typeof module]&&module&&!module.nodeType&&module;var u=n&&l&&"object"==typeof global&&global;!u||u.global!==u&&u.window!==u&&u.self!==u||(r=u);var q=Math.pow(2,53)-1,B=/\bOpera/;u=Object.prototype;var m=u.hasOwnProperty,t=u.toString,w=p();"function"==typeof define&&"object"==typeof define.amd&&define.amd?(r.platform=w,define(function(){return w})):n&&
l?e(w,function(a,b){n[b]=a}):r.platform=w}).call(this);
function buildIOSMeta(){for(var a=[{name:"viewport",content:"width=device-width, height=device-height, initial-scale=1, minimum-scale=1, maximum-scale=1, user-scalable=no"},{name:"apple-mobile-web-app-capable",content:"yes"},{name:"apple-mobile-web-app-status-bar-style",content:"black"}],c=0;c<a.length;c++){var b=document.createElement("meta");b.name=a[c].name;b.content=a[c].content;var e=window.document.head.querySelector('meta[name="'+b.name+'"]');e&&e.parentNode.removeChild(e);window.document.head.appendChild(b)}}
function hideIOSFullscreenPanel(){jQuery(".xxx-ios-fullscreen-message").css("display","none");jQuery(".xxx-ios-fullscreen-scroll").css("display","none");jQuery(".xxx-game-iframe-full").removeClass("xxx-game-iframe-iphone-se")}function buildIOSFullscreenPanel(){jQuery("body").append('<div class="xxx-ios-fullscreen-message"><div class="xxx-ios-fullscreen-swipe"></div></div><div class="xxx-ios-fullscreen-scroll"></div>')}
function showIOSFullscreenPanel(){jQuery(".xxx-ios-fullscreen-message").css("display","block");jQuery(".xxx-ios-fullscreen-scroll").css("display","block")}
function __iosResize(){window.scrollTo(0,0);console.log(window.devicePixelRatio);console.log(window.innerWidth);console.log(window.innerHeight);if("iPhone"===platform.product)switch(window.devicePixelRatio){case 2:switch(window.innerWidth){case 568:320!==window.innerHeight&&jQuery(".xxx-game-iframe-full").addClass("xxx-game-iframe-iphone-se");break;case 667:375===window.innerHeight?hideIOSFullscreenPanel():showIOSFullscreenPanel();break;case 808:414===window.innerHeight?hideIOSFullscreenPanel():showIOSFullscreenPanel();
break;default:hideIOSFullscreenPanel()}break;case 3:switch(window.innerWidth){case 736:414===window.innerHeight?hideIOSFullscreenPanel():showIOSFullscreenPanel();break;case 724:375===window.innerHeight?hideIOSFullscreenPanel():showIOSFullscreenPanel();break;case 808:414===window.innerHeight?hideIOSFullscreenPanel():showIOSFullscreenPanel();break;default:hideIOSFullscreenPanel()}break;default:hideIOSFullscreenPanel()}}function iosResize(){__iosResize();setTimeout(function(){__iosResize()},500)}
function iosInIframe(){try{return window.self!==window.top}catch(a){return!0}}function isIOSLessThen13(){var a=platform.os,c=a.family.toLowerCase();a=parseFloat(a.version);return"ios"===c&&13>a?!0:!1}$(document).ready(function(){platform&&"iPhone"===platform.product&&"safari"===platform.name.toLowerCase()&&isIOSLessThen13()&&!iosInIframe()&&(buildIOSFullscreenPanel(),buildIOSMeta())});
jQuery(window).resize(function(){platform&&"iPhone"===platform.product&&"safari"===platform.name.toLowerCase()&&isIOSLessThen13()&&!iosInIframe()&&iosResize()});
(function(){var a="undefined"!==typeof window&&"undefined"!==typeof window.document?window.document:{},c="undefined"!==typeof module&&module.exports,b=function(){for(var b,c=["requestFullscreen exitFullscreen fullscreenElement fullscreenEnabled fullscreenchange fullscreenerror".split(" "),"webkitRequestFullscreen webkitExitFullscreen webkitFullscreenElement webkitFullscreenEnabled webkitfullscreenchange webkitfullscreenerror".split(" "),"webkitRequestFullScreen webkitCancelFullScreen webkitCurrentFullScreenElement webkitCancelFullScreen webkitfullscreenchange webkitfullscreenerror".split(" "),
"mozRequestFullScreen mozCancelFullScreen mozFullScreenElement mozFullScreenEnabled mozfullscreenchange mozfullscreenerror".split(" "),"msRequestFullscreen msExitFullscreen msFullscreenElement msFullscreenEnabled MSFullscreenChange MSFullscreenError".split(" ")],d=0,e=c.length,l={};d<e;d++)if((b=c[d])&&b[1]in a){for(d=0;d<b.length;d++)l[c[0][d]]=b[d];return l}return!1}(),e={change:b.fullscreenchange,error:b.fullscreenerror},d={request:function(c){return new Promise(function(d,e){var f=function(){this.off("change",
f);d()}.bind(this);this.on("change",f);c=c||a.documentElement;Promise.resolve(c[b.requestFullscreen]())["catch"](e)}.bind(this))},exit:function(){return new Promise(function(c,d){if(this.isFullscreen){var e=function(){this.off("change",e);c()}.bind(this);this.on("change",e);Promise.resolve(a[b.exitFullscreen]())["catch"](d)}else c()}.bind(this))},toggle:function(a){return this.isFullscreen?this.exit():this.request(a)},onchange:function(a){this.on("change",a)},onerror:function(a){this.on("error",a)},
on:function(b,c){var d=e[b];d&&a.addEventListener(d,c,!1)},off:function(b,c){var d=e[b];d&&a.removeEventListener(d,c,!1)},raw:b};b?(Object.defineProperties(d,{isFullscreen:{get:function(){return!!a[b.fullscreenElement]}},element:{enumerable:!0,get:function(){return a[b.fullscreenElement]}},isEnabled:{enumerable:!0,get:function(){return!!a[b.fullscreenEnabled]}}}),c?module.exports=d:window.screenfull=d):c?module.exports={isEnabled:!1}:window.screenfull={isEnabled:!1}})();
var s_iScaleFactor=1,s_iOffsetX,s_iOffsetY,s_bIsIphone=!1;
(function(a){(jQuery.browser=jQuery.browser||{}).mobile=/android|avantgo|bada\/|blackberry|blazer|compal|elaine|fennec|hiptop|iemobile|ip(ad|hone|od)|iris|kindle|lge |maemo|midp|mmp|netfront|opera m(ob|in)i|palm( os)?|phone|p(ixi|re)\/|plucker|pocket|psp|symbian|tablet|treo|up\.(browser|link)|vodafone|wap|webos|windows (ce|phone)|xda|xiino/i.test(a)||/1207|6310|6590|3gso|4thp|50[1-6]i|770s|802s|a wa|abac|ac(er|oo|s\-)|ai(ko|rn)|al(av|ca|co)|amoi|an(ex|ny|yw)|aptu|ar(ch|go)|as(te|us)|attw|au(di|\-m|r |s )|avan|be(ck|ll|nq)|bi(lb|rd)|bl(ac|az)|br(e|v)w|bumb|bw\-(n|u)|c55\/|capi|ccwa|cdm\-|cell|chtm|cldc|cmd\-|co(mp|nd)|craw|da(it|ll|ng)|dbte|dc\-s|devi|dica|dmob|do(c|p)o|ds(12|\-d)|el(49|ai)|em(l2|ul)|er(ic|k0)|esl8|ez([4-7]0|os|wa|ze)|fetc|fly(\-|_)|g1 u|g560|gene|gf\-5|g\-mo|go(\.w|od)|gr(ad|un)|haie|hcit|hd\-(m|p|t)|hei\-|hi(pt|ta)|hp( i|ip)|hs\-c|ht(c(\-| |_|a|g|p|s|t)|tp)|hu(aw|tc)|i\-(20|go|ma)|i230|iac( |\-|\/)|ibro|idea|ig01|ikom|im1k|inno|ipaq|iris|ja(t|v)a|jbro|jemu|jigs|kddi|keji|kgt( |\/)|klon|kpt |kwc\-|kyo(c|k)|le(no|xi)|lg( g|\/(k|l|u)|50|54|e\-|e\/|\-[a-w])|libw|lynx|m1\-w|m3ga|m50\/|ma(te|ui|xo)|mc(01|21|ca)|m\-cr|me(di|rc|ri)|mi(o8|oa|ts)|mmef|mo(01|02|bi|de|do|t(\-| |o|v)|zz)|mt(50|p1|v )|mwbp|mywa|n10[0-2]|n20[2-3]|n30(0|2)|n50(0|2|5)|n7(0(0|1)|10)|ne((c|m)\-|on|tf|wf|wg|wt)|nok(6|i)|nzph|o2im|op(ti|wv)|oran|owg1|p800|pan(a|d|t)|pdxg|pg(13|\-([1-8]|c))|phil|pire|pl(ay|uc)|pn\-2|po(ck|rt|se)|prox|psio|pt\-g|qa\-a|qc(07|12|21|32|60|\-[2-7]|i\-)|qtek|r380|r600|raks|rim9|ro(ve|zo)|s55\/|sa(ge|ma|mm|ms|ny|va)|sc(01|h\-|oo|p\-)|sdk\/|se(c(\-|0|1)|47|mc|nd|ri)|sgh\-|shar|sie(\-|m)|sk\-0|sl(45|id)|sm(al|ar|b3|it|t5)|so(ft|ny)|sp(01|h\-|v\-|v )|sy(01|mb)|t2(18|50)|t6(00|10|18)|ta(gt|lk)|tcl\-|tdg\-|tel(i|m)|tim\-|t\-mo|to(pl|sh)|ts(70|m\-|m3|m5)|tx\-9|up(\.b|g1|si)|utst|v400|v750|veri|vi(rg|te)|vk(40|5[0-3]|\-v)|vm40|voda|vulc|vx(52|53|60|61|70|80|81|83|85|98)|w3c(\-| )|webc|whit|wi(g |nc|nw)|wmlb|wonu|x700|xda(\-|2|g)|yas\-|your|zeto|zte\-/i.test(a.substr(0,4))})(navigator.userAgent||
navigator.vendor||window.opera);$(window).resize(function(){sizeHandler()});function trace(a){console.log(a)}function hexToRgb(a){return(a=/^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(a))?{r:parseInt(a[1],16),g:parseInt(a[2],16),b:parseInt(a[3],16)}:null}function checkIfiOS(){return navigator.userAgent.match(/(iPad|iPhone|iPod)/g)?!0:!1}
function getSize(a){var c=a.toLowerCase(),b=window.document,e=b.documentElement;if(void 0===window["inner"+a])a=e["client"+a];else if(window["inner"+a]!=e["client"+a]){var d=b.createElement("body");d.id="vpw-test-b";d.style.cssText="overflow:scroll";var f=b.createElement("div");f.id="vpw-test-d";f.style.cssText="position:absolute;top:-1000px";f.innerHTML="<style>@media("+c+":"+e["client"+a]+"px){body#vpw-test-b div#vpw-test-d{"+c+":7px!important}}</style>";d.appendChild(f);e.insertBefore(d,b.head);
a=7==f["offset"+a]?e["client"+a]:window["inner"+a];e.removeChild(d)}else a=window["inner"+a];return a}window.addEventListener("orientationchange",onOrientationChange);function onOrientationChange(){window.matchMedia("(orientation: portrait)").matches&&sizeHandler();window.matchMedia("(orientation: landscape)").matches&&sizeHandler()}function isChrome(){return/Chrome/.test(navigator.userAgent)&&/Google Inc/.test(navigator.vendor)}function isMobile(){return isIpad()?!0:jQuery.browser.mobile}
function isIpad(){var a=-1!==navigator.userAgent.toLowerCase().indexOf("ipad");return!a&&navigator.userAgent.match(/Mac/)&&navigator.maxTouchPoints&&2<navigator.maxTouchPoints?!0:a}function isIOS(){for(var a="iPad Simulator;iPhone Simulator;iPod Simulator;iPad;iPhone;iPod".split(";");a.length;)if(navigator.platform===a.pop())return s_bIsIphone=!0;return s_bIsIphone=!1}function getIOSWindowHeight(){return document.documentElement.clientWidth/window.innerWidth*window.innerHeight}
function getHeightOfIOSToolbars(){var a=(0===window.orientation?screen.height:screen.width)-getIOSWindowHeight();return 1<a?a:0}
function sizeHandler(){window.scrollTo(0,1);if($("#canvas")){var a="safari"===platform.name.toLowerCase()?getIOSWindowHeight():getSize("Height");var c=getSize("Width");_checkOrientation(c,a);var b=Math.min(a/CANVAS_HEIGHT,c/CANVAS_WIDTH),e=Math.round(CANVAS_WIDTH*b);b=Math.round(CANVAS_HEIGHT*b);if(b<a){var d=a-b;b+=d;e+=CANVAS_WIDTH/CANVAS_HEIGHT*d}else e<c&&(d=c-e,e+=d,b+=CANVAS_HEIGHT/CANVAS_WIDTH*d);d=a/2-b/2;var f=c/2-e/2,g=CANVAS_WIDTH/e;if(f*g<-EDGEBOARD_X||d*g<-EDGEBOARD_Y)b=Math.min(a/(CANVAS_HEIGHT-
2*EDGEBOARD_Y),c/(CANVAS_WIDTH-2*EDGEBOARD_X)),e=Math.round(CANVAS_WIDTH*b),b=Math.round(CANVAS_HEIGHT*b),d=(a-b)/2,f=(c-e)/2,g=CANVAS_WIDTH/e;s_iOffsetX=-1*f*g;s_iOffsetY=-1*d*g;0<=d&&(s_iOffsetY=0);0<=f&&(s_iOffsetX=0);null!==s_oInterface&&s_oInterface.refreshButtonPos(s_iOffsetX,s_iOffsetY);null!==s_oMenu&&s_oMenu.refreshButtonPos(s_iOffsetX,s_iOffsetY);null!==s_oModeMenu&&s_oModeMenu.refreshButtonPos(s_iOffsetX,s_iOffsetY);$("#canvas").css("width",e+"px");$("#canvas").css("height",b+"px");0>d||
(d=(a-b)/2);$("#canvas").css("top",d+"px");$("#canvas").css("left",f+"px");$("#draw_canvas").css("width",e+"px");$("#draw_canvas").css("height",b+"px");0>d||(d=(a-b)/2);$("#draw_canvas").css("top",d+"px");$("#draw_canvas").css("left",f+"px");$("#interactivecanvas").css("width",e+"px");$("#interactivecanvas").css("height",b+"px");0>d||(d=(a-b)/2);$("#interactivecanvas").css("top",d+"px");$("#interactivecanvas").css("left",f+"px");s_oCanvasLeft=$("#canvas").offset().left;s_oCanvasTop=$("#canvas").offset().top}}
function _checkOrientation(a,c){s_bMobile&&ENABLE_CHECK_ORIENTATION&&(a>c?"landscape"===$(".orientation-msg-container").attr("data-orientation")?($(".orientation-msg-container").css("display","none"),s_oMain.startUpdate()):($(".orientation-msg-container").css("display","block"),s_oMain.stopUpdate()):"portrait"===$(".orientation-msg-container").attr("data-orientation")?($(".orientation-msg-container").css("display","none"),s_oMain.startUpdate()):($(".orientation-msg-container").css("display","block"),
s_oMain.stopUpdate()))}function playSound(a,c,b){return!1===DISABLE_SOUND_MOBILE||!1===s_bMobile?(s_aSounds[a].play(),s_aSounds[a].volume(c),s_aSounds[a].loop(b),s_aSounds[a]):null}function stopSound(a){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||s_aSounds[a].stop()}function setVolume(a,c){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||s_aSounds[a].volume(c)}function setMute(a,c){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||s_aSounds[a].mute(c)}
function fadeSound(a,c,b,e){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||s_aSounds[a].fade(c,b,e)}function soundPlaying(a){if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)return s_aSounds[a].playing()}function createBitmap(a,c,b){var e=new createjs.Bitmap(a),d=new createjs.Graphics;c&&b?d.beginFill("#fff").drawRect(0,0,c,b):d.beginFill("#ff0").drawRect(0,0,a.width,a.height);a=new createjs.Shape(d);e.hitArea=a;return e}
function createSprite(a,c,b,e,d,f){a=null!==c?new createjs.Sprite(a,c):new createjs.Sprite(a);c=new createjs.Graphics;c.beginFill("#000000").drawRect(-b,-e,d,f);b=new createjs.Shape(c);a.hitArea=b;return a}function pad(a,c,b){a+="";return a.length>=c?a:Array(c-a.length+1).join(b||"0")+a}function randomFloatBetween(a,c,b){"undefined"===typeof b&&(b=2);return parseFloat(Math.min(a+Math.random()*(c-a),c).toFixed(b))}
function rotateVector2D(a,c){var b=c.getX()*Math.cos(a)+c.getY()*Math.sin(a),e=c.getX()*-Math.sin(a)+c.getY()*Math.cos(a);c.set(b,e)}function tweenVectorsOnX(a,c,b){return a+b*(c-a)}function shuffle(a){for(var c=a.length,b,e;0!==c;)e=Math.floor(Math.random()*c),--c,b=a[c],a[c]=a[e],a[e]=b;return a}function bubbleSort(a){do{var c=!1;for(var b=0;b<a.length-1;b++)a[b]>a[b+1]&&(c=a[b],a[b]=a[b+1],a[b+1]=c,c=!0)}while(c)}function compare(a,c){return a.index>c.index?-1:a.index<c.index?1:0}
function easeLinear(a,c,b,e){return b*a/e+c}function easeInQuad(a,c,b,e){return b*(a/=e)*a+c}function easeInSine(a,c,b,e){return-b*Math.cos(a/e*(Math.PI/2))+b+c}function easeInCubic(a,c,b,e){return b*(a/=e)*a*a+c}function getTrajectoryPoint(a,c){var b=new createjs.Point,e=(1-a)*(1-a),d=a*a;b.x=e*c.start.x+2*(1-a)*a*c.traj.x+d*c.end.x;b.y=e*c.start.y+2*(1-a)*a*c.traj.y+d*c.end.y;return b}
function formatTime(a){a/=1E3;var c=Math.floor(a/60);a=parseFloat(a-60*c).toFixed(1);var b="";b=10>c?b+("0"+c+":"):b+(c+":");return 10>a?b+("0"+a):b+a}function degreesToRadians(a){return a*Math.PI/180}function checkRectCollision(a,c){var b=getBounds(a,.9);var e=getBounds(c,.98);return calculateIntersection(b,e)}
function calculateIntersection(a,c){var b,e,d,f;var g=a.x+(b=a.width/2);var h=a.y+(e=a.height/2);var p=c.x+(d=c.width/2);var l=c.y+(f=c.height/2);g=Math.abs(g-p)-(b+d);h=Math.abs(h-l)-(e+f);return 0>g&&0>h?(g=Math.min(Math.min(a.width,c.width),-g),h=Math.min(Math.min(a.height,c.height),-h),{x:Math.max(a.x,c.x),y:Math.max(a.y,c.y),width:g,height:h,rect1:a,rect2:c}):null}
function getBounds(a,c){var b={x:Infinity,y:Infinity,width:0,height:0};if(a instanceof createjs.Container){b.x2=-Infinity;b.y2=-Infinity;var e=a.children,d=e.length,f;for(f=0;f<d;f++){var g=getBounds(e[f],1);g.x<b.x&&(b.x=g.x);g.y<b.y&&(b.y=g.y);g.x+g.width>b.x2&&(b.x2=g.x+g.width);g.y+g.height>b.y2&&(b.y2=g.y+g.height)}Infinity==b.x&&(b.x=0);Infinity==b.y&&(b.y=0);Infinity==b.x2&&(b.x2=0);Infinity==b.y2&&(b.y2=0);b.width=b.x2-b.x;b.height=b.y2-b.y;delete b.x2;delete b.y2}else{if(a instanceof createjs.Bitmap){d=
a.sourceRect||a.image;f=d.width*c;var h=d.height*c}else if(a instanceof createjs.Sprite)if(a.spriteSheet._frames&&a.spriteSheet._frames[a.currentFrame]&&a.spriteSheet._frames[a.currentFrame].image){d=a.spriteSheet.getFrame(a.currentFrame);f=d.rect.width;h=d.rect.height;e=d.regX;var p=d.regY}else b.x=a.x||0,b.y=a.y||0;else b.x=a.x||0,b.y=a.y||0;e=e||0;f=f||0;p=p||0;h=h||0;b.regX=e;b.regY=p;d=a.localToGlobal(0-e,0-p);g=a.localToGlobal(f-e,h-p);f=a.localToGlobal(f-e,0-p);e=a.localToGlobal(0-e,h-p);b.x=
Math.min(Math.min(Math.min(d.x,g.x),f.x),e.x);b.y=Math.min(Math.min(Math.min(d.y,g.y),f.y),e.y);b.width=Math.max(Math.max(Math.max(d.x,g.x),f.x),e.x)-b.x;b.height=Math.max(Math.max(Math.max(d.y,g.y),f.y),e.y)-b.y}return b}function NoClickDelay(a){this.element=a;window.Touch&&this.element.addEventListener("touchstart",this,!1)}
NoClickDelay.prototype={handleEvent:function(a){switch(a.type){case "touchstart":this.onTouchStart(a);break;case "touchmove":this.onTouchMove(a);break;case "touchend":this.onTouchEnd(a)}},onTouchStart:function(a){a.preventDefault();this.moved=!1;this.element.addEventListener("touchmove",this,!1);this.element.addEventListener("touchend",this,!1)},onTouchMove:function(a){this.moved=!0},onTouchEnd:function(a){this.element.removeEventListener("touchmove",this,!1);this.element.removeEventListener("touchend",
this,!1);if(!this.moved){a=document.elementFromPoint(a.changedTouches[0].clientX,a.changedTouches[0].clientY);3==a.nodeType&&(a=a.parentNode);var c=document.createEvent("MouseEvents");c.initEvent("click",!0,!0);a.dispatchEvent(c)}}};
(function(){function a(a){var b={focus:"visible",focusin:"visible",pageshow:"visible",blur:"hidden",focusout:"hidden",pagehide:"hidden"};a=a||window.event;a.type in b?document.body.className=b[a.type]:(document.body.className=this[c]?"hidden":"visible","hidden"===document.body.className?s_oMain.stopUpdate():s_oMain.startUpdate())}var c="hidden";c in document?document.addEventListener("visibilitychange",a):(c="mozHidden")in document?document.addEventListener("mozvisibilitychange",a):(c="webkitHidden")in
document?document.addEventListener("webkitvisibilitychange",a):(c="msHidden")in document?document.addEventListener("msvisibilitychange",a):"onfocusin"in document?document.onfocusin=document.onfocusout=a:window.onpageshow=window.onpagehide=window.onfocus=window.onblur=a})();function ctlArcadeResume(){null!==s_oMain&&s_oMain.startUpdate()}function ctlArcadePause(){null!==s_oMain&&s_oMain.stopUpdate()}
function getParamValue(a){for(var c=window.location.search.substring(1).split("&"),b=0;b<c.length;b++){var e=c[b].split("=");if(e[0]==a)return e[1]}}function fullscreenHandler(){ENABLE_FULLSCREEN&&screenfull.isEnabled&&(s_bFullscreen=screenfull.isFullscreen,null!==s_oInterface&&s_oInterface.resetFullscreenBut(),null!==s_oModeMenu&&s_oModeMenu.resetFullscreenBut(),null!==s_oMenu&&s_oMenu.resetFullscreenBut())}
if(screenfull.isEnabled)screenfull.on("change",function(){s_bFullscreen=screenfull.isFullscreen;null!==s_oInterface&&s_oInterface.resetFullscreenBut();null!==s_oModeMenu&&s_oModeMenu.resetFullscreenBut();null!==s_oMenu&&s_oMenu.resetFullscreenBut()});
function CSpriteLibrary(){var a={},c,b,e,d,f,g;this.init=function(a,p,l){c={};e=b=0;d=a;f=p;g=l};this.addSprite=function(d,e){if(!a.hasOwnProperty(d)){var f=new Image;a[d]=c[d]={szPath:e,oSprite:f,bLoaded:!1};b++}};this.getSprite=function(b){return a.hasOwnProperty(b)?a[b].oSprite:null};this._onSpritesLoaded=function(){b=0;f.call(g)};this._onSpriteLoaded=function(){d.call(g);++e===b&&this._onSpritesLoaded()};this.loadSprites=function(){for(var a in c)c[a].oSprite.oSpriteLibrary=this,c[a].oSprite.szKey=
a,c[a].oSprite.onload=function(){this.oSpriteLibrary.setLoaded(this.szKey);this.oSpriteLibrary._onSpriteLoaded(this.szKey)},c[a].oSprite.onerror=function(a){var b=a.currentTarget;setTimeout(function(){c[b.szKey].oSprite.src=c[b.szKey].szPath},500)},c[a].oSprite.src=c[a].szPath};this.setLoaded=function(b){a[b].bLoaded=!0};this.isLoaded=function(b){return a[b].bLoaded};this.getNumSprites=function(){return b}}
var CANVAS_WIDTH=1920,CANVAS_HEIGHT=1080,EDGEBOARD_X=200,EDGEBOARD_Y=35,FPS=30,FPS_TIME=1E3/FPS,DISABLE_SOUND_MOBILE=!1,SOUNDTRACK_VOLUME_IN_GAME=1,PRIMARY_FONT="walibi",SECONDARY_FONT="Arial",STATE_LOADING=0,STATE_MENU=1,STATE_HELP=1,STATE_GAME=3,ON_MOUSE_DOWN=0,ON_MOUSE_UP=1,ON_MOUSE_OVER=2,ON_MOUSE_OUT=3,ON_DRAG_START=4,ON_DRAG_END=5,COLORS=[],MIN_STROKE,MAX_STROKE,AD_SHOW_COUNTER,ENABLE_PRINT,ENABLE_SAVEIMAGE,TEXT_PLAY="PLAY",TEXT_HELP1="PLEASE, PICK A COLOR",TEXT_CHOOSE="SELECT THE PICTURE YOU WANT TO PAINT",
TEXT_DEVELOPED="DEVELOPED BY";
function CPreloader(){var a,c,b,e,d,f,g;this._init=function(){s_oSpriteLibrary.init(this._onImagesLoaded,this._onAllImagesLoaded,this);s_oSpriteLibrary.addSprite("bg_menu","./sprites/bg_menu.jpg");s_oSpriteLibrary.addSprite("progress_bar","./sprites/progress_bar.png");s_oSpriteLibrary.loadSprites();g=new createjs.Container;s_oStage.addChild(g)};this.unload=function(){g.removeAllChildren()};this.hide=function(){var a=this;setTimeout(function(){createjs.Tween.get(f).to({alpha:1},500).call(function(){a.unload();
s_oMain.gotoMenu()})},1E3)};this._onImagesLoaded=function(){};this._onAllImagesLoaded=function(){this.attachSprites();s_oMain.preloaderReady()};this.attachSprites=function(){var h=createBitmap(s_oSpriteLibrary.getSprite("bg_menu"));g.addChild(h);h=s_oSpriteLibrary.getSprite("progress_bar");e=createBitmap(h);e.x=CANVAS_WIDTH/2-h.width/2;e.y=CANVAS_HEIGHT-170;g.addChild(e);a=h.width;c=h.height;d=new createjs.Shape;d.graphics.beginFill("rgba(255,255,255,0.01)").drawRect(e.x,e.y,1,c);g.addChild(d);e.mask=
d;b=new createjs.Text("","30px "+SECONDARY_FONT,"#fff");b.x=CANVAS_WIDTH/2;b.y=CANVAS_HEIGHT-125;b.shadow=new createjs.Shadow("#000",2,2,2);b.textBaseline="alphabetic";b.textAlign="center";g.addChild(b);f=new createjs.Shape;f.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);f.alpha=0;g.addChild(f)};this.refreshLoader=function(f){b.text=f+"%";d.graphics.clear();f=Math.floor(f*a/100);d.graphics.beginFill("rgba(255,255,255,0.01)").drawRect(e.x,e.y,f,c)};this._init()}
function CMain(a){var c,b=0,e=0,d;this.initContainer=function(){s_oDrawCanvas=document.getElementById("draw_canvas");s_oDrawStage=new createjs.Stage(s_oDrawCanvas);s_oCanvas=document.getElementById("canvas");s_oStage=new createjs.Stage(s_oCanvas);s_oInteractiveCanvas=document.getElementById("interactivecanvas");s_oInteractiveStage=new createjs.Stage(s_oInteractiveCanvas);createjs.Touch.enable(s_oInteractiveStage,!0);s_bMobile=isMobile();!1===s_bMobile&&(s_oStage.enableMouseOver(FPS),s_oInteractiveStage.enableMouseOver(FPS),
$("body").on("contextmenu","#canvas",function(a){return!1}));s_iPrevTime=(new Date).getTime();createjs.Ticker.addEventListener("tick",this._update);createjs.Ticker.framerate=FPS;navigator.userAgent.match(/Windows Phone/i)&&(DISABLE_SOUND_MOBILE=!0);s_oSpriteLibrary=new CSpriteLibrary;d=new CPreloader};this.preloaderReady=function(){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||this._initSounds();this._loadImages();c=!0};this.soundLoaded=function(){b++;d.refreshLoader(Math.floor(b/e*100));b===e&&s_oMain._onAllResourcesLoaded()};
this._initSounds=function(){Howler.mute(!s_bAudioActive);s_aSoundsInfo=[];s_aSoundsInfo.push({path:"./sounds/",filename:"soundtrack",loop:!0,volume:1,ingamename:"soundtrack"});s_aSoundsInfo.push({path:"./sounds/",filename:"press_button",loop:!1,volume:1,ingamename:"click"});e+=s_aSoundsInfo.length;s_aSounds=[];for(var a=0;a<s_aSoundsInfo.length;a++)this.tryToLoadSound(s_aSoundsInfo[a],!1)};this.tryToLoadSound=function(a,b){setTimeout(function(){s_aSounds[a.ingamename]=new Howl({src:[a.path+a.filename+
".mp3"],autoplay:!1,preload:!0,loop:a.loop,volume:a.volume,onload:s_oMain.soundLoaded,onloaderror:function(a,b){for(var c=0;c<s_aSoundsInfo.length;c++)if(a===s_aSounds[s_aSoundsInfo[c].ingamename]._sounds[0]._id){s_oMain.tryToLoadSound(s_aSoundsInfo[c],!0);break}},onplayerror:function(a){for(var b=0;b<s_aSoundsInfo.length;b++)if(a===s_aSounds[s_aSoundsInfo[b].ingamename]._sounds[0]._id){s_aSounds[s_aSoundsInfo[b].ingamename].once("unlock",function(){s_aSounds[s_aSoundsInfo[b].ingamename].play();"soundtrack"===
s_aSoundsInfo[b].ingamename&&null!==s_oGame&&setVolume("soundtrack",SOUNDTRACK_VOLUME_IN_GAME)});break}}})},b?200:0)};this._loadImages=function(){s_oSpriteLibrary.init(this._onImagesLoaded,this._onAllImagesLoaded,this);s_oSpriteLibrary.addSprite("but_play","./sprites/but_play.png");s_oSpriteLibrary.addSprite("ctl_logo","./sprites/ctl_logo.png");s_oSpriteLibrary.addSprite("but_fullscreen","./sprites/but_fullscreen.png");s_oSpriteLibrary.addSprite("but_credits","./sprites/but_credits.png");s_oSpriteLibrary.addSprite("msg_box",
"./sprites/msg_box.png");s_oSpriteLibrary.addSprite("bg_menu","./sprites/bg_menu.jpg");s_oSpriteLibrary.addSprite("bg_modemenu","./sprites/bg_modemenu.jpg");s_oSpriteLibrary.addSprite("bg_game","./sprites/bg_game.jpg");s_oSpriteLibrary.addSprite("but_exit","./sprites/but_exit.png");s_oSpriteLibrary.addSprite("audio_icon","./sprites/audio_icon.png");s_oSpriteLibrary.addSprite("but_save","./sprites/but_save.png");s_oSpriteLibrary.addSprite("but_print","./sprites/but_print.png");s_oSpriteLibrary.addSprite("but_restart",
"./sprites/but_restart.png");s_oSpriteLibrary.addSprite("eraser","./sprites/eraser.png");s_oSpriteLibrary.addSprite("sliderbox","./sprites/sliderbox.png");s_oSpriteLibrary.addSprite("slider","./sprites/slider.png");s_oSpriteLibrary.addSprite("pen","./sprites/pen.png");s_oSpriteLibrary.addSprite("canvas_drawing","./sprites/drawcanvas.jpg");s_oSpriteLibrary.addSprite("drawcanvas_frame","./sprites/drawcanvas_frame.png");s_oSpriteLibrary.addSprite("image1","./sprites/image1.png");s_oSpriteLibrary.addSprite("image2",
"./sprites/image2.png");s_oSpriteLibrary.addSprite("image3","./sprites/image3.png");s_oSpriteLibrary.addSprite("image4","./sprites/image4.png");s_oSpriteLibrary.addSprite("image5","./sprites/image5.png");s_oSpriteLibrary.addSprite("image6","./sprites/image6.png");e+=s_oSpriteLibrary.getNumSprites();s_oSpriteLibrary.loadSprites()};this._onImagesLoaded=function(){b++;d.refreshLoader(Math.floor(b/e*100));b===e&&s_oMain._onAllResourcesLoaded()};this._onAllImagesLoaded=function(){};this.onAllPreloaderImagesLoaded=
function(){this._loadImages()};this._onAllResourcesLoaded=function(){d.unload();playSound("soundtrack",1,!0);this.gotoMenu()};this.gotoMenu=function(){new CMenu};this.gotoModeMenu=function(){new CModeMenu};this.gotoGame=function(a){s_szCurDraw=a;new CGame(f)};this.gotoHelp=function(){new CHelp};this.stopUpdate=function(){c=!1;createjs.Ticker.paused=!0;$("#block_game").css("display","block");Howler.mute(!0)};this.startUpdate=function(){s_iPrevTime=(new Date).getTime();c=!0;createjs.Ticker.paused=!1;
$("#block_game").css("display","none");s_bAudioActive&&Howler.mute(!1)};this._update=function(){if(!1!==c){var a=(new Date).getTime();s_iTimeElaps=a-s_iPrevTime;s_iCntTime+=s_iTimeElaps;s_iCntFps++;s_iPrevTime=a;1E3<=s_iCntTime&&(s_iCurFps=s_iCntFps,s_iCntTime-=1E3,s_iCntFps=0)}};ENABLE_FULLSCREEN=a.fullscreen;ENABLE_CHECK_ORIENTATION=a.check_orientation;ENABLE_PRINT=a.show_print_button;ENABLE_SAVEIMAGE=a.show_save_button;s_bAudioActive=a.audio_enable_on_startup;var f=a;s_oMain=this;this.initContainer()}
var s_bMobile,s_bAudioActive=!1,s_iCntTime=0,s_iTimeElaps=0,s_iPrevTime=0,s_iCntFps=0,s_iCurFps=0,s_szCurDraw,s_bFullscreen=!1,s_oStage,s_oMain,s_oSpriteLibrary,s_oSoundTrack,s_oCanvas,s_oDrawCanvas,s_oDrawStage,s_oInteractiveCanvas,s_oInteractiveStage,s_aSounds=[],s_aSoundsInfo=[];
function CTextButton(a,c,b,e,d,f,g){var h,p,l,r,n;this._init=function(a,b,c,d,e,f,g){h=[];p=[];var m=createBitmap(c),q=Math.ceil(g/20);n=new createjs.Text(d," "+g+"px "+e,"#ff4200");n.textAlign="center";n.textBaseline="alphabetic";var t=n.getBounds();n.x=c.width/2+q;n.y=Math.floor(c.height/2)+t.height/3+q;r=new createjs.Text(d," "+g+"px "+e,f);r.textAlign="center";r.textBaseline="alphabetic";t=r.getBounds();r.x=c.width/2;r.y=Math.floor(c.height/2)+t.height/3;l=new createjs.Container;l.x=a;l.y=b;l.regX=
c.width/2;l.regY=c.height/2;l.cursor="pointer";l.addChild(m,n,r);s_oInteractiveStage.addChild(l);s_oInteractiveStage.update();this._initListener()};this.unload=function(){l.off("mousedown");l.off("pressup");s_oInteractiveStage.removeChild(l)};this.setVisible=function(a){l.visible=a};this._initListener=function(){l.on("mousedown",this.buttonDown);l.on("pressup",this.buttonRelease)};this.addEventListener=function(a,b,c){h[a]=b;p[a]=c};this.buttonRelease=function(){l.scaleX=1;l.scaleY=1;h[ON_MOUSE_UP]&&
h[ON_MOUSE_UP].call(p[ON_MOUSE_UP]);s_oInteractiveStage.update()};this.buttonDown=function(){l.scaleX=.9;l.scaleY=.9;playSound("click",1,!1);h[ON_MOUSE_DOWN]&&h[ON_MOUSE_DOWN].call(p[ON_MOUSE_DOWN]);s_oInteractiveStage.update()};this.setTextPosition=function(a){r.y=a;n.y=a+2};this.setPosition=function(a,b){l.x=a;l.y=b};this.setX=function(a){l.x=a};this.setY=function(a){l.y=a};this.getButtonImage=function(){return l};this.getX=function(){return l.x};this.getY=function(){return l.y};this._init(a,c,
b,e,d,f,g);return this}
function CToggle(a,c,b,e){var d,f,g,h;this._init=function(a,b,c,e){f=[];g=[];var l=new createjs.SpriteSheet({images:[c],frames:{width:c.width/2,height:c.height,regX:c.width/2/2,regY:c.height/2},animations:{state_true:[0],state_false:[1]}});d=e;h=createSprite(l,"state_"+d,c.width/2/2,c.height/2,c.width/2,c.height);h.x=a;h.y=b;h.cursor="pointer";h.stop();s_oInteractiveStage.addChild(h);this._initListener()};this.unload=function(){h.off("mousedown",this.buttonDown);h.off("pressup",this.buttonRelease);
s_oInteractiveStage.removeChild(h)};this._initListener=function(){h.on("mousedown",this.buttonDown);h.on("pressup",this.buttonRelease)};this.addEventListener=function(a,b,c){f[a]=b;g[a]=c};this.setActive=function(a){d=a;h.gotoAndStop("state_"+d)};this.buttonRelease=function(){h.scaleX=1;h.scaleY=1;d=!d;h.gotoAndStop("state_"+d);f[ON_MOUSE_UP]&&f[ON_MOUSE_UP].call(g[ON_MOUSE_UP],d);s_oInteractiveStage.update()};this.buttonDown=function(){h.scaleX=.9;h.scaleY=.9;playSound("click",1,!1);f[ON_MOUSE_DOWN]&&
f[ON_MOUSE_DOWN].call(g[ON_MOUSE_DOWN]);s_oInteractiveStage.update()};this.setPosition=function(a,b){h.x=a;h.y=b};this._init(a,c,b,e)}
function CSliderBox(a,c,b,e){var d,f=!1,g,h,p;this._init=function(a,b,c,e){d=!1;g=new createjs.Container;g.x=a;g.y=b;g.cursor="pointer";e.addChild(g);a=new createjs.SpriteSheet({images:[c],frames:{width:c.width/2,height:c.height,regX:c.width/2/2,regY:c.height/2},animations:{state_true:[0],state_false:[1]}});h=createSprite(a,"state_"+f,c.width/2/2,c.height/2,c.width/2,c.height);p=new createjs.Shape;p.graphics.beginFill("white").drawCircle(0,0,.5*s_oInterface.getStroke());g.addChild(h,p);this._initListener()};
this.unload=function(){g.off("mousedown",this.buttonDown);g.off("pressup",this.buttonRelease);e.removeChild(g)};this.setVisible=function(a){g.visible=a};this.setSliderVisible=function(a){d=a};this.setCircle=function(a,b){p.graphics.clear();null===b&&(b="#FFFFFF");p.graphics.beginFill(b).drawCircle(0,0,.5*a)};this._initListener=function(){g.on("mousedown",this.buttonDown);g.on("pressup",this.buttonRelease)};this.buttonRelease=function(){g.scaleX=1;g.scaleY=1;d=!d;s_oInterface.setSliderVisible(d);d||
s_oGame.setTempColor();f=!f;h.gotoAndStop("state_"+f);s_oInteractiveStage.update()};this.buttonDown=function(){g.scaleX=.9;g.scaleY=.9;d||s_oGame.saveTempColor();playSound("click",1,!1);s_oInterface.disableStroke();s_oInteractiveStage.update()};this.setPosition=function(a,b){g.x=a;g.y=b};this.setX=function(a){g.x=a};this.setY=function(a){g.y=a};this.getButtonImage=function(){return g};this.getX=function(){return g.x};this.getY=function(){return g.y};this.setActive=function(a){(f=a)||h.gotoAndStop("state_"+
f)};this._init(a,c,b,e);return this}
function CSlider(a,c,b,e,d,f){var g,h,p,l,r,n,u,q;this._init=function(a,b,c,d,e,f){g=Math.round((e-d)/2);q=new createjs.Container;q.x=a;q.y=b;f.addChild(q);a=new createjs.SpriteSheet({images:[c],frames:{width:c.width/3,height:c.height,regX:c.width/3/2,regY:c.height/2},animations:{pointer:[0],bar:[1],label:[2]}});r=createSprite(a,"bar",c.width/3/2,c.height/2,c.width/3,c.height);r.stop();q.addChild(r);n=createSprite(a,"label",c.width/3/2,c.height/2,c.width/3,c.height);n.stop();n.y=-c.height/2-c.width/
3/2;q.addChild(n);b=c.width/3;u=new CTLText(q,-(b/2),-c.height/2-b/2-15,b,30,24,"center","#ffffff",PRIMARY_FONT,1,2,2,g,!0,!0,!1,!1);l=createSprite(a,"pointer",c.width/3/2,c.height/2,c.width/3,c.height);l.stop();q.addChild(l);p=c.height/2-c.width/3/2;h=-c.height/2+c.width/3/2;q.visible=!1;this._initListener()};this.unload=function(){l.off("pressmove",this.buttonDown);l.off("pressup",this.buttonRelease);f.removeChild(q)};this._initListener=function(){l.on("pressmove",this.buttonDown);l.on("pressup",
this.buttonRelease)};this.buttonRelease=function(){s_oGame.sliderMoving(!1);s_oInterface.setSliderVisible(!1);s_oInterface.setStroke(g);s_oInterface.restartStroke();s_oInteractiveStage.update()};this.buttonDown=function(a){s_oGame.sliderMoving(!0);a=q.globalToLocal(a.stageX,a.stageY);l.y=a.y;a.y>p?l.y=p:a.y<h&&(l.y=h);B.setValue();u.refreshText(g);s_oInterface.setCircleImage(g,s_oGame.getTempColor());s_oInteractiveStage.update()};this.setValue=function(){g=(l.y-p)/(h-p)*(d-e)+e;g=Math.round(g)};this.getValue=
function(){return g};this.setLabel=function(){};this.setPosition=function(a,b){l.x=a;l.y=b};this.setVisible=function(a){q.visible=a;s_oInteractiveStage.update()};this.getVisible=function(){return q.visible};var B=this;this._init(a,c,b,e,d,f)}
function CGfxButton(a,c,b){var e,d,f;this._init=function(a,b,c){e=[];d=[];f=createBitmap(c);f.x=a;f.y=b;f.regX=c.width/2;f.regY=c.height/2;f.cursor="pointer";s_oInteractiveStage.addChild(f);s_oInteractiveStage.update();this._initListener()};this.unload=function(){f.off("mousedown",this.buttonDown);f.off("pressup",this.buttonRelease);s_oInteractiveStage.removeChild(f)};this.setVisible=function(a){f.visible=a};this._initListener=function(){f.on("mousedown",this.buttonDown);f.on("pressup",this.buttonRelease)};
this.addEventListener=function(a,b,c){e[a]=b;d[a]=c};this.buttonRelease=function(){f.scaleX=1;f.scaleY=1;e[ON_MOUSE_UP]&&e[ON_MOUSE_UP].call(d[ON_MOUSE_UP]);s_oInteractiveStage.update()};this.buttonDown=function(){f.scaleX=.9;f.scaleY=.9;playSound("click",1,!1);e[ON_MOUSE_DOWN]&&e[ON_MOUSE_DOWN].call(d[ON_MOUSE_DOWN]);s_oInteractiveStage.update()};this.setPosition=function(a,b){f.x=a;f.y=b};this.setX=function(a){f.x=a};this.setY=function(a){f.y=a};this.getButtonImage=function(){return f};this.getX=
function(){return f.x};this.getY=function(){return f.y};this._init(a,c,b);return this}
function CMenu(){var a,c,b,e,d,f,g,h,p,l,r,n=null,u=null;this._init=function(){g=createBitmap(s_oSpriteLibrary.getSprite("bg_menu"));s_oInteractiveStage.addChild(g);var q=s_oSpriteLibrary.getSprite("but_play");h=new CTextButton(CANVAS_WIDTH/2,CANVAS_HEIGHT-200,q,TEXT_PLAY,"walibi","#eedc20",80);h.addEventListener(ON_MOUSE_UP,this._onButPlayRelease,this);if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)q=s_oSpriteLibrary.getSprite("audio_icon"),d=CANVAS_WIDTH-q.height/2-10,f=q.height/2+10,p=new CToggle(d,
f,q,s_bAudioActive),p.addEventListener(ON_MOUSE_UP,this._onAudioToggle,this);q=s_oSpriteLibrary.getSprite("but_credits");b=q.width/2+12;e=q.height/2+16;l=new CGfxButton(b,e,q,s_oInteractiveStage);l.addEventListener(ON_MOUSE_UP,this._onCreditsBut,this);q=window.document;var B=q.documentElement;n=B.requestFullscreen||B.mozRequestFullScreen||B.webkitRequestFullScreen||B.msRequestFullscreen;u=q.exitFullscreen||q.mozCancelFullScreen||q.webkitExitFullscreen||q.msExitFullscreen;!1===ENABLE_FULLSCREEN&&(n=
!1);n&&screenfull.isEnabled&&(q=s_oSpriteLibrary.getSprite("but_fullscreen"),a=b+q.width/2+12,c=q.height/2+16,r=new CToggle(a,c,q,s_bFullscreen,s_oInteractiveStage),r.addEventListener(ON_MOUSE_UP,this._onFullscreenRelease,this));this.refreshButtonPos(s_iOffsetX,s_iOffsetY)};this.unload=function(){h.unload();h=null;l.unload();if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)p.unload(),p=null;n&&screenfull.isEnabled&&r.unload();s_oInteractiveStage.removeChild(g);s_oMenu=g=null};this.refreshButtonPos=function(g,
h){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||p.setPosition(d-g,h+f);l.setPosition(b+g,h+e);n&&screenfull.isEnabled&&r.setPosition(a+g,c+h);setTimeout(function(){s_oInteractiveStage.update()},300)};this.resetFullscreenBut=function(){n&&screenfull.isEnabled&&r.setActive(s_bFullscreen)};this._onFullscreenRelease=function(){s_bFullscreen?u.call(window.document):n.call(window.document.documentElement);sizeHandler()};this._onCreditsBut=function(){new CCreditsPanel};this._onAudioToggle=function(){Howler.mute(s_bAudioActive);
s_bAudioActive=!s_bAudioActive};this._onButPlayRelease=function(){this.unload();$(s_oMain).trigger("start_session");s_oMain.gotoModeMenu()};s_oMenu=this;this._init()}var s_oMenu=null;
function CModeMenu(){var a,c,b,e,d,f,g,h,p,l,r,n,u,q=null,B=null;this._init=function(){var m=s_oSpriteLibrary.getSprite("bg_modemenu");d=createBitmap(m);s_oInteractiveStage.addChild(d);var t=1460,w=70;m=CANVAS_WIDTH/2;var z=CANVAS_HEIGHT/2+30;(new CTLText(s_oInteractiveStage,m-t/2,z-w/2,t,w,60,"center","#ff4200",PRIMARY_FONT,1,2,2,TEXT_CHOOSE,!0,!0,!1,!1)).setOutline(10);new CTLText(s_oInteractiveStage,m-t/2,z-w/2,t,w,60,"center","#eedc20",PRIMARY_FONT,1,2,2,TEXT_CHOOSE,!0,!0,!1,!1);h=new createjs.Container;
h.x=CANVAS_WIDTH/2-500;h.y=CANVAS_HEIGHT/2-190;h.scaleX=.3;h.scaleY=.3;h.cursor="pointer";h.on("click",this._onImageClicked,this,!1,"image1");m=s_oSpriteLibrary.getSprite("image1");t=m.width;w=m.height;z=new createjs.Shape;z.graphics.beginFill("#ffffff").drawRect(-t/2,-w/2,t,w);h.addChild(z);m=createBitmap(m);m.regX=t/2;m.regY=w/2;h.addChild(m);z=new createjs.Shape;z.graphics.beginStroke("#000000").setStrokeStyle(10).drawRect(-t/2,-w/2,t,w);h.addChild(z);p=new createjs.Container;p.x=CANVAS_WIDTH/
2;p.y=CANVAS_HEIGHT/2-190;p.scaleX=.3;p.scaleY=.3;p.cursor="pointer";p.on("click",this._onImageClicked,this,!1,"image2");m=s_oSpriteLibrary.getSprite("image2");t=m.width;w=m.height;z=new createjs.Shape;z.graphics.beginFill("#ffffff").drawRect(-t/2,-w/2,t,w);p.addChild(z);m=createBitmap(m);m.regX=t/2;m.regY=w/2;p.addChild(m);z=new createjs.Shape;z.graphics.beginStroke("#000000").setStrokeStyle(10).drawRect(-t/2,-w/2,t,w);p.addChild(z);l=new createjs.Container;l.x=CANVAS_WIDTH/2+500;l.y=CANVAS_HEIGHT/
2-190;l.scaleX=.3;l.scaleY=.3;l.cursor="pointer";l.on("click",this._onImageClicked,this,!1,"image3");m=s_oSpriteLibrary.getSprite("image3");t=m.width;w=m.height;z=new createjs.Shape;z.graphics.beginFill("#ffffff").drawRect(-t/2,-w/2,t,w);l.addChild(z);m=createBitmap(m);m.regX=t/2;m.regY=w/2;l.addChild(m);z=new createjs.Shape;z.graphics.beginStroke("#000000").setStrokeStyle(10).drawRect(-t/2,-w/2,t,w);l.addChild(z);r=new createjs.Container;r.x=CANVAS_WIDTH/2-500;r.y=CANVAS_HEIGHT/2+230;r.scaleX=.3;
r.scaleY=.3;r.cursor="pointer";r.on("click",this._onImageClicked,this,!1,"image4");m=s_oSpriteLibrary.getSprite("image4");t=m.width;w=m.height;z=new createjs.Shape;z.graphics.beginFill("#ffffff").drawRect(-t/2,-w/2,t,w);r.addChild(z);m=createBitmap(m);m.regX=t/2;m.regY=w/2;r.addChild(m);z=new createjs.Shape;z.graphics.beginStroke("#000000").setStrokeStyle(10).drawRect(-t/2,-w/2,t,w);r.addChild(z);n=new createjs.Container;n.x=CANVAS_WIDTH/2;n.y=CANVAS_HEIGHT/2+230;n.scaleX=.3;n.scaleY=.3;n.cursor=
"pointer";n.on("click",this._onImageClicked,this,!1,"image5");m=s_oSpriteLibrary.getSprite("image5");t=m.width;w=m.height;z=new createjs.Shape;z.graphics.beginFill("#ffffff").drawRect(-t/2,-w/2,t,w);n.addChild(z);m=createBitmap(m);m.regX=t/2;m.regY=w/2;n.addChild(m);z=new createjs.Shape;z.graphics.beginStroke("#000000").setStrokeStyle(10).drawRect(-t/2,-w/2,t,w);n.addChild(z);u=new createjs.Container;u.x=CANVAS_WIDTH/2+500;u.y=CANVAS_HEIGHT/2+230;u.scaleX=.3;u.scaleY=.3;u.cursor="pointer";u.on("click",
this._onImageClicked,this,!1,"image6");m=s_oSpriteLibrary.getSprite("image6");t=m.width;w=m.height;z=new createjs.Shape;z.graphics.beginFill("#ffffff").drawRect(-t/2,-w/2,t,w);u.addChild(z);m=createBitmap(m);m.regX=t/2;m.regY=w/2;u.addChild(m);z=new createjs.Shape;z.graphics.beginStroke("#000000").setStrokeStyle(10).drawRect(-t/2,-w/2,t,w);u.addChild(z);s_oInteractiveStage.addChild(h,p,l,r,n,u);if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)m=s_oSpriteLibrary.getSprite("audio_icon"),b=CANVAS_WIDTH-
m.height/2-10,e=m.height/2+10,f=new CToggle(b,e,m,s_bAudioActive),f.addEventListener(ON_MOUSE_UP,this._onAudioToggle,this);t=window.document;w=t.documentElement;q=w.requestFullscreen||w.mozRequestFullScreen||w.webkitRequestFullScreen||w.msRequestFullscreen;B=t.exitFullscreen||t.mozCancelFullScreen||t.webkitExitFullscreen||t.msExitFullscreen;!1===ENABLE_FULLSCREEN&&(q=!1);m=s_oSpriteLibrary.getSprite("but_fullscreen");!1===DISABLE_SOUND_MOBILE||!1===s_bMobile?(a=b-m.width/2-10,c=m.height/2+10):(a=
CANVAS_WIDTH-m.height/2-10,c=m.height/2+10);q&&screenfull.isEnabled&&(g=new CToggle(a,c,m,s_bFullscreen,s_oStage),g.addEventListener(ON_MOUSE_UP,this._onFullscreenRelease,this));this.refreshButtonPos(s_iOffsetX,s_iOffsetY)};this.unload=function(){if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)f.unload(),f=null;q&&screenfull.isEnabled&&g.unload();s_oInteractiveStage.removeAllChildren();h.removeAllEventListeners();p.removeAllEventListeners();l.removeAllEventListeners();r.removeAllEventListeners();n.removeAllEventListeners();
n.removeAllEventListeners();s_oModeMenu=null;s_oInteractiveStage.update()};this.refreshButtonPos=function(d,h){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||f.setPosition(b-d,h+e);q&&screenfull.isEnabled&&g.setPosition(a-d,c+h);s_oInteractiveStage.update()};this.resetFullscreenBut=function(){q&&screenfull.isEnabled&&g.setActive(s_bFullscreen)};this._onFullscreenRelease=function(){s_bFullscreen?B.call(window.document):q.call(window.document.documentElement);sizeHandler()};this._onAudioToggle=function(){Howler.mute(s_bAudioActive);
s_bAudioActive=!s_bAudioActive};this._onImageClicked=function(a,b){this.unload();$(s_oMain).trigger("start_level",1);s_oMain.gotoGame(b);playSound("click",1,!1)};s_oModeMenu=this;this._init()}var s_oModeMenu=null;
function CGame(a){var c,b,e,d,f,g,h,p,l,r,n,u,q,B,m,t,w,z,G,N,E,J=s_oDrawStage.canvas.getContext("2d");this._init=function(){h=10;f=null;r=0;u=createBitmap(s_oSpriteLibrary.getSprite("bg_game"));s_oDrawStage.addChild(u);t=new createjs.Container;t.x=CANVAS_WIDTH/2;t.y=CANVAS_HEIGHT/2;s_oDrawStage.addChild(t);var a=s_oSpriteLibrary.getSprite("canvas_drawing");p=a.width;l=a.height;B=createBitmap(a);t.addChild(B);t.regX=p/2;t.regY=l/2;c=CANVAS_WIDTH/2-p/2+.5*h;b=CANVAS_HEIGHT/2-l/2+.5*h;e=p+CANVAS_WIDTH/
2-p/2-.5*h;d=l+CANVAS_HEIGHT/2-l/2-.5*h;q=new createjs.Shape;q.graphics.setStrokeStyle(h,"round","round");z=new createjs.Container;s_oStage.addChild(z);a=s_oSpriteLibrary.getSprite(s_szCurDraw);w=createBitmap(a);w.x=CANVAS_WIDTH/2;w.y=CANVAS_HEIGHT/2;w.regX=a.width/2;w.regY=a.height/2;s_oInteractiveStage.addChild(w);z.addChild(q);a=s_oSpriteLibrary.getSprite("drawcanvas_frame");m=createBitmap(a);m.x=CANVAS_WIDTH/2;m.y=CANVAS_HEIGHT/2;m.regX=a.width/2;m.regY=a.height/2;s_oInteractiveStage.addChild(m);
a=CANVAS_WIDTH/2;var g=CANVAS_HEIGHT/2+30;E=new CTLText(s_oInteractiveStage,a-400,g-35,800,70,60,"center","#ff4200",PRIMARY_FONT,1,2,2,TEXT_HELP1,!0,!0,!1,!1);E.setOutline(10);E.setVisible(!1);N=new CTLText(s_oInteractiveStage,a-400,g-35,800,70,60,"center","#eedc20",PRIMARY_FONT,1,2,2,TEXT_HELP1,!0,!0,!1,!1);N.setVisible(!1);G=new createjs.Shape;G.graphics.beginFill("rgba(255,255,255,0.01)").drawRect(-580,-410,1160,820);G.x=CANVAS_WIDTH/2;G.y=CANVAS_HEIGHT/2;G.on("mousedown",this._setAdvice);s_oInteractiveStage.addChild(G);
s_bMobile?(window.navigator.msPointerEnabled&&(_iContTouchMS=0),s_oInteractiveStage.addEventListener("stagemousedown",this.onMouseStart,!1),s_oInteractiveStage.addEventListener("stagemouseup",this.onMouseEnd,!1)):(s_oInteractiveStage.addEventListener("stagemousedown",this.onMouseStart),s_oInteractiveStage.addEventListener("stagemouseup",this.onMouseEnd));n=new CInterface;s_oDrawStage.update();s_oInteractiveStage.update()};this.printImg=function(){var a=s_oSpriteLibrary.getSprite(s_szCurDraw),b=s_oSpriteLibrary.getSprite(s_szCurDraw);
b=createBitmap(a);b.x=CANVAS_WIDTH/2;b.y=CANVAS_HEIGHT/2;b.regX=a.width/2;b.regY=a.height/2;w.visible=!1;s_oDrawStage.addChild(b);u.visible=!1;s_oDrawStage.update();try{var c=document.getElementById("draw_canvas").toDataURL();a="<!DOCTYPE html>";a+="<html>";a+='<img src="'+c+'">';a+="</html>";var d=window.open("","","width=1920,height=1080");d.document.open();d.document.write(a);d.document.close();d.onload=function(){d.focus();d.print();d.close()}}catch(A){console.log(A)}s_oDrawStage.removeChild(b);
w.visible=!0;u.visible=!0;s_oDrawStage.update()};this.saveImg=function(){var a=s_oSpriteLibrary.getSprite(s_szCurDraw);s_oSpriteLibrary.getSprite(s_szCurDraw);var b=createBitmap(a);b.x=CANVAS_WIDTH/2;b.y=CANVAS_HEIGHT/2;b.regX=a.width/2;b.regY=a.height/2;w.visible=!1;s_oDrawStage.addChild(b);u.visible=!1;s_oDrawStage.update();try{var c=document.createElement("a");document.body.appendChild(c);var d=s_szCurDraw+pad(Math.round(1E3*Math.random()),4)+".png";c.download=d;c.href=s_oDrawCanvas.toDataURL("image/png");
c.click()}catch(A){console.log(A)}s_oDrawStage.removeChild(b);w.visible=!0;u.visible=!0;s_oDrawStage.update()};this.sliderMoving=function(a){};this.tryShowAd=function(){r++;r===AD_SHOW_COUNTER&&(r=0,$(s_oMain).trigger("show_interlevel_ad"))};this.setColor=function(a){f=a;this.tryShowAd()};this.getColor=function(){return f};this.saveTempColor=function(){g=f};this.setTempColor=function(){f=g};this.getTempColor=function(){return g};this.setStroke=function(a){h=a;c=CANVAS_WIDTH/2-p/2+.5*h;b=CANVAS_HEIGHT/
2-l/2+.5*h;e=p+CANVAS_WIDTH/2-p/2-.5*h;d=l+CANVAS_HEIGHT/2-l/2-.5*h};this.deleteStroke=function(a){f=a?"#ffffff":null};this.initStroke=function(){q=new createjs.Shape;q.graphics.setStrokeStyle(h,"round","round");q.graphics.beginStroke(f);z.addChild(q)};this.onMouseStart=function(a){a=a||window.event;!a.primary||s_oInteractiveStage.mouseX<c||s_oInteractiveStage.mouseX>e||s_oInteractiveStage.mouseY<b||s_oInteractiveStage.mouseY>d||(s_oGame.initStroke(),q.graphics.moveTo(s_oInteractiveStage.mouseX,s_oInteractiveStage.mouseY),
s_oInteractiveStage.addEventListener("stagemousemove",I.onMouseMove))};this.onMouseMove=function(a){!a.primary||s_oInteractiveStage.mouseX<c||s_oInteractiveStage.mouseX>e||s_oInteractiveStage.mouseY<b||s_oInteractiveStage.mouseY>d||(q.graphics.lineTo(s_oInteractiveStage.mouseX,s_oInteractiveStage.mouseY),checkIfiOS()?q.draw(J):s_oStage.update())};this.onMouseEnd=function(a){a.primary&&(s_oDrawStage.addChild(q),q.graphics.endStroke(),z.removeChild(q),s_oDrawStage.update(),s_oStage.update(),s_oInteractiveStage.removeEventListener("stagemousemove",
I.onMouseMove))};this.restartGame=function(){s_oDrawStage.removeAllChildren();q.graphics.clear();s_oDrawStage.addChild(u);s_oDrawStage.addChild(t);var a=s_oSpriteLibrary.getSprite("canvas_drawing");p=a.width;l=a.height;B=createBitmap(a);t.addChild(B);s_oDrawStage.update();s_oStage.update()};this.unload=function(){n.unload();G.off("mousedown",this._setAdvice);createjs.Tween.removeAllTweens();s_oStage.removeAllChildren();s_oStage.update()};this.onExit=function(){this.unload();s_oMain.gotoMenu()};this._setAdvice=
function(){null!==f||n.getSliderVisible()||I.colorAdvice(!0)};this.colorAdvice=function(a){N.setVisible(a);E.setVisible(a);s_oInteractiveStage.update()};this.update=function(){};s_oGame=this;COLORS=a.colors;MIN_STROKE=a.min_stroke_size;MAX_STROKE=a.max_stroke_size;AD_SHOW_COUNTER=a.ad_show_counter;var I=this;this._init()}var s_oGame;
function CInterface(){var a,c,b,e,d,f,g,h,p,l,r,n,u,q,B,m,t,w,z,G,N=null,E,J,I,y,O,M=null,T=null;this._init=function(){q=u=null;var A=s_oSpriteLibrary.getSprite("but_exit");r=CANVAS_WIDTH-A.height/2-20;n=A.height/2+10;t=new CGfxButton(r,n,A,!0);t.addEventListener(ON_MOUSE_UP,this._onExit,this);p=CANVAS_WIDTH-A.width/2-20;l=250;if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)A=s_oSpriteLibrary.getSprite("audio_icon"),m=new CToggle(p,l,A,s_bAudioActive),m.addEventListener(ON_MOUSE_UP,this._onAudioToggle,
this);A=window.document;var H=A.documentElement;M=H.requestFullscreen||H.mozRequestFullScreen||H.webkitRequestFullScreen||H.msRequestFullscreen;T=A.exitFullscreen||A.mozCancelFullScreen||A.webkitExitFullscreen||A.msExitFullscreen;!1===ENABLE_FULLSCREEN&&(M=!1);A=s_oSpriteLibrary.getSprite("but_fullscreen");!1===DISABLE_SOUND_MOBILE||!1===s_bMobile?(a=p,c=l+A.width/2+10):(a=CANVAS_WIDTH-A.width/4-20,c=250);M&&screenfull.isEnabled&&(O=new CToggle(a,c,A,s_bFullscreen,s_oStage),O.addEventListener(ON_MOUSE_UP,
this._onFullscreenRelease,this));A=s_oSpriteLibrary.getSprite("but_save");H=A.height/2+10;g=A.height/2+20;h=H;w=new CGfxButton(g,h,A,!0);w.addEventListener(ON_MOUSE_UP,this._onSaveAsImg,this);ENABLE_SAVEIMAGE?H+=A.height+10:w.setVisible(!1);A=s_oSpriteLibrary.getSprite("but_print");d=A.height/2+20;f=H;z=new CGfxButton(d,f,A,!0);z.addEventListener(ON_MOUSE_UP,this._onPrinteAsImg,this);ENABLE_PRINT?H+=A.height+10:z.setVisible(!1);A=s_oSpriteLibrary.getSprite("but_restart");b=A.height/2+20;e=H;G=new CGfxButton(b,
e,A,!0);G.addEventListener(ON_MOUSE_UP,this._onButRestartRelease,this);E=new createjs.Container;A=1E3-EDGEBOARD_Y;E.x=CANVAS_WIDTH/2;E.y=A;B=[];for(A=0;A<COLORS.length;A++)B[A]=new CPen(50*A,0,COLORS[A],A,E);s_oInteractiveStage.addChild(E);B[COLORS.length]=new CPen(-100,0,"eraser",COLORS.length,E);J=new createjs.Container;J.x=1600;J.y=1E3;s_oInteractiveStage.addChild(J);A=s_oSpriteLibrary.getSprite("slider");I=new CSlider(0,-125,A,MIN_STROKE,MAX_STROKE,J);A=s_oSpriteLibrary.getSprite("sliderbox");
y=new CSliderBox(0,0,A,J);A=I.getValue();this.setStroke(A);A=E.getBounds();E.regX=(A.width-100)/2;this.refreshButtonPos(s_iOffsetX,s_iOffsetY);s_oInteractiveStage.update()};this.unload=function(){if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)m.unload(),m=null;for(var a=0;a<B.length;a++)B[a].unload();M&&screenfull.isEnabled&&O.unload();t.unload();w.unload();z.unload();G.unload();I.unload();y.unload();s_oInterface=null};this.disableStroke=function(){s_oGame.deleteStroke(!1)};this.restartStroke=function(){s_oGame.setColor(u)};
this.setStroke=function(a){s_oGame.setStroke(a)};this.getStroke=function(){return I.getValue()};this.setActivePen=function(a,b){this.setSliderVisible(!1);s_oGame.setColor(a);s_oGame.colorAdvice(!1);u=a;y.setActive(!1);null!==q&&B[q].setActive(!1);q=b};this.getCircleSize=function(){return I.getValue()};this.setCircleImage=function(a,b){y.setCircle(a,b)};this.setSliderVisible=function(a){I.setVisible(a);y.setSliderVisible(a);a||y.setActive(!1)};this.getSliderVisible=function(){return I.getVisible()};
this._onSaveAsImg=function(){s_oGame.saveImg()};this._onPrinteAsImg=function(){s_oGame.printImg()};this.refreshButtonPos=function(q,u){t.setPosition(r-q,u+n);!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||m.setPosition(p-q,u+l);w.setPosition(g+q,u+h);z.setPosition(d+q,u+f);G.setPosition(b+q,u+e);M&&screenfull.isEnabled&&O.setPosition(a-q,c+u);s_oInteractiveStage.update()};this._onButHelpRelease=function(){N=new CHelpPanel};this._onButRestartRelease=function(){$(s_oMain).trigger("restart_level",1);$(s_oMain).trigger("show_interlevel_ad");
s_oGame.restartGame()};this.onExitFromHelp=function(){N.unload()};this.resetFullscreenBut=function(){M&&screenfull.isEnabled&&O.setActive(s_bFullscreen)};this._onFullscreenRelease=function(){s_bFullscreen?T.call(window.document):M.call(window.document.documentElement);sizeHandler()};this._onAudioToggle=function(){Howler.mute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};this._onExit=function(){$(s_oMain).trigger("end_level",1);$(s_oMain).trigger("end_session");$(s_oMain).trigger("show_interlevel_ad");
s_oGame.onExit()};s_oInterface=this;this._init();return this}var s_oInterface=null;
function CPen(a,c,b,e,d){var f,g,h,p;this._init=function(a,b,c,d,e){f=50;g=d;p=e;if("eraser"===c)d=s_oSpriteLibrary.getSprite("eraser"),h=createBitmap(d),h.x=a,h.y=b,h.cache(0,0,100,200),h.on("mousedown",this._setEraser);else{d=s_oSpriteLibrary.getSprite("pen");h=createBitmap(d);h.x=a;h.y=b;a=hexToRgb(c).r;b=hexToRgb(c).g;c=hexToRgb(c).b;try{var l=new createjs.ColorFilter(a/255,b/255,c/255,1);h.filters=[l];h.cache(0,0,50,200)}catch(t){console.log(t)}h.on("mousedown",this._setColor)}h.cursor="pointer";
p.addChild(h)};this.unload=function(){h.off("mousedown",this._setColor);p.removeChild(h)};this._setColor=function(){playSound("click",1,!1);s_oInterface.setActivePen(b,g);l.setActive(!0)};this._setEraser=function(){playSound("click",1,!1);s_oInterface.setActivePen("#FFFFFF",g);l.setActive(!0)};this.setActive=function(a){h.y=a?c-f:c;try{h.updateCache()}catch(n){console.log(n)}s_oInterface.setCircleImage(s_oInterface.getCircleSize(),s_oGame.getColor());s_oInteractiveStage.update()};var l=this;this._init(a,
c,b,e,d)}
function CCreditsPanel(){var a,c,b,e;this._init=function(){a=new createjs.Shape;a.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);a.alpha=.7;a.on("mousedown",function(){});s_oInteractiveStage.addChild(a);c=new createjs.Container;s_oInteractiveStage.addChild(c);var d=s_oSpriteLibrary.getSprite("msg_box"),f=createBitmap(d);f.regX=d.width/2;f.regY=d.height/2;c.addChild(f);c.x=CANVAS_WIDTH/2;c.y=CANVAS_HEIGHT/2;f=d.width-400;var g=50;new CTLText(c,-(f/2),-120-g/2,f,g,40,"center",
"#008df0",PRIMARY_FONT,1,2,2,TEXT_DEVELOPED,!0,!0,!1,!1);f=d.width-300;g=50;new CTLText(c,-(f/2),100-g/2,f,g,40,"center","#008df0",PRIMARY_FONT,1,2,2,"www.codethislab.com",!0,!0,!1,!1);d=s_oSpriteLibrary.getSprite("ctl_logo");e=createBitmap(d);e.on("mousedown",this._onLogoButRelease);e.regX=d.width/2;e.regY=d.height/2;c.addChild(e);d=s_oSpriteLibrary.getSprite("but_exit");b=new CGfxButton(1320,330,d,c);b.addEventListener(ON_MOUSE_UP,this.unload,this)};this.unload=function(){s_oInteractiveStage.removeChild(a);
s_oInteractiveStage.removeChild(c);b.unload();a.off("mousedown",function(){});e.off("mousedown",this._onLogoButRelease)};this._onLogoButRelease=function(){window.open("http://www.codethislab.com/index.php?&l=en")};this._onMoreGamesReleased=function(){window.open("http://codecanyon.net/collections/5409142-games")};this._init()}
CTLText.prototype={constructor:CTLText,__autofit:function(){if(this._bFitText){for(var a=this._iFontSize;(this._oText.getBounds().height>this._iHeight-2*this._iPaddingV||this._oText.getBounds().width>this._iWidth-2*this._iPaddingH)&&!(a--,this._oText.font=a+"px "+this._szFont,this._oText.lineHeight=Math.round(a*this._fLineHeightFactor),this.__updateY(),this.__verticalAlign(),8>a););this._iFontSize=a}},__verticalAlign:function(){if(this._bVerticalAlign){var a=this._oText.getBounds().height;this._oText.y-=
(a-this._iHeight)/2+this._iPaddingV}},__updateY:function(){this._oText.y=this._y+this._iPaddingV;switch(this._oText.textBaseline){case "middle":this._oText.y+=this._oText.lineHeight/2+(this._iFontSize*this._fLineHeightFactor-this._iFontSize)}},__createText:function(a){this._bDebug&&(this._oDebugShape=new createjs.Shape,this._oDebugShape.graphics.beginFill("rgba(255,0,0,0.5)").drawRect(this._x,this._y,this._iWidth,this._iHeight),this._oContainer.addChild(this._oDebugShape));this._oText=new createjs.Text(a,
this._iFontSize+"px "+this._szFont,this._szColor);this._oText.textBaseline="middle";this._oText.lineHeight=Math.round(this._iFontSize*this._fLineHeightFactor);this._oText.textAlign=this._szAlign;this._oText.lineWidth=this._bMultiline?this._iWidth-2*this._iPaddingH:null;switch(this._szAlign){case "center":this._oText.x=this._x+this._iWidth/2;break;case "left":this._oText.x=this._x+this._iPaddingH;break;case "right":this._oText.x=this._x+this._iWidth-this._iPaddingH}this._oContainer.addChild(this._oText);
this.refreshText(a)},setVisible:function(a){this._oText.visible=a},setVerticalAlign:function(a){this._bVerticalAlign=a},setOutline:function(a){null!==this._oText&&(this._oText.outline=a)},setShadow:function(a,c,b,e){null!==this._oText&&(this._oText.shadow=new createjs.Shadow(a,c,b,e))},setColor:function(a){this._oText.color=a},setAlpha:function(a){this._oText.alpha=a},setY:function(a){this._y=this._oText.y=a},removeTweens:function(){createjs.Tween.removeTweens(this._oText)},getText:function(){return this._oText},
getY:function(){return this._y},getFontSize:function(){return this._iFontSize},refreshText:function(a){""===a&&(a=" ");null===this._oText&&this.__createText(a);this._oText.text=a;this._oText.font=this._iFontSize+"px "+this._szFont;this._oText.lineHeight=Math.round(this._iFontSize*this._fLineHeightFactor);this.__autofit();this.__updateY();this.__verticalAlign()}};
function CTLText(a,c,b,e,d,f,g,h,p,l,r,n,u,q,B,m,t){this._oContainer=a;this._x=c;this._y=b;this._iWidth=e;this._iHeight=d;this._bMultiline=m;this._iFontSize=f;this._szAlign=g;this._szColor=h;this._szFont=p;this._iPaddingH=r;this._iPaddingV=n;this._bVerticalAlign=B;this._bFitText=q;this._bDebug=t;this._oDebugShape=null;this._fLineHeightFactor=l;this._oText=null;u&&this.__createText(u)};